// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identity

import (
	"context"

	"github.com/guxiao/community-and-home/services/identity/rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckPermissionReq            = pb.CheckPermissionReq
	CheckPermissionResp           = pb.CheckPermissionResp
	GetPropertyBindingsReq        = pb.GetPropertyBindingsReq
	GetPropertyBindingsResp       = pb.GetPropertyBindingsResp
	GetRolesByIdsReq              = pb.GetRolesByIdsReq
	GetRolesByIdsResp             = pb.GetRolesByIdsResp
	GetUserPermissionsReq         = pb.GetUserPermissionsReq
	GetUserPermissionsResp        = pb.GetUserPermissionsResp
	GetUserReq                    = pb.GetUserReq
	GetUserResp                   = pb.GetUserResp
	GetUserRolesReq               = pb.GetUserRolesReq
	GetUserRolesResp              = pb.GetUserRolesResp
	GetUserVerificationStatusReq  = pb.GetUserVerificationStatusReq
	GetUserVerificationStatusResp = pb.GetUserVerificationStatusResp
	GetUsersByIdsReq              = pb.GetUsersByIdsReq
	GetUsersByIdsResp             = pb.GetUsersByIdsResp
	LoginReq                      = pb.LoginReq
	LoginResp                     = pb.LoginResp
	LoginSmsReq                   = pb.LoginSmsReq
	LoginSmsResp                  = pb.LoginSmsResp
	LogoutReq                     = pb.LogoutReq
	LogoutResp                    = pb.LogoutResp
	PropertyBinding               = pb.PropertyBinding
	RefreshTokenReq               = pb.RefreshTokenReq
	RefreshTokenResp              = pb.RefreshTokenResp
	RegisterReq                   = pb.RegisterReq
	RegisterResp                  = pb.RegisterResp
	Role                          = pb.Role
	User                          = pb.User
	ValidatePropertyAccessReq     = pb.ValidatePropertyAccessReq
	ValidatePropertyAccessResp    = pb.ValidatePropertyAccessResp
	ValidateTokenReq              = pb.ValidateTokenReq
	ValidateTokenResp             = pb.ValidateTokenResp

	Identity interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		LoginSms(ctx context.Context, in *LoginSmsReq, opts ...grpc.CallOption) (*LoginSmsResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		GetUsersByIds(ctx context.Context, in *GetUsersByIdsReq, opts ...grpc.CallOption) (*GetUsersByIdsResp, error)
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
		GetUserPermissions(ctx context.Context, in *GetUserPermissionsReq, opts ...grpc.CallOption) (*GetUserPermissionsResp, error)
		GetRolesByIds(ctx context.Context, in *GetRolesByIdsReq, opts ...grpc.CallOption) (*GetRolesByIdsResp, error)
		GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error)
		// Verification and property related methods
		GetUserVerificationStatus(ctx context.Context, in *GetUserVerificationStatusReq, opts ...grpc.CallOption) (*GetUserVerificationStatusResp, error)
		GetPropertyBindings(ctx context.Context, in *GetPropertyBindingsReq, opts ...grpc.CallOption) (*GetPropertyBindingsResp, error)
		ValidatePropertyAccess(ctx context.Context, in *ValidatePropertyAccessReq, opts ...grpc.CallOption) (*ValidatePropertyAccessResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

func (m *defaultIdentity) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultIdentity) LoginSms(ctx context.Context, in *LoginSmsReq, opts ...grpc.CallOption) (*LoginSmsResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.LoginSms(ctx, in, opts...)
}

func (m *defaultIdentity) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultIdentity) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultIdentity) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultIdentity) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultIdentity) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultIdentity) GetUsersByIds(ctx context.Context, in *GetUsersByIdsReq, opts ...grpc.CallOption) (*GetUsersByIdsResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUsersByIds(ctx, in, opts...)
}

func (m *defaultIdentity) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}

func (m *defaultIdentity) GetUserPermissions(ctx context.Context, in *GetUserPermissionsReq, opts ...grpc.CallOption) (*GetUserPermissionsResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUserPermissions(ctx, in, opts...)
}

func (m *defaultIdentity) GetRolesByIds(ctx context.Context, in *GetRolesByIdsReq, opts ...grpc.CallOption) (*GetRolesByIdsResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetRolesByIds(ctx, in, opts...)
}

func (m *defaultIdentity) GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUserRoles(ctx, in, opts...)
}

// Verification and property related methods
func (m *defaultIdentity) GetUserVerificationStatus(ctx context.Context, in *GetUserVerificationStatusReq, opts ...grpc.CallOption) (*GetUserVerificationStatusResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUserVerificationStatus(ctx, in, opts...)
}

func (m *defaultIdentity) GetPropertyBindings(ctx context.Context, in *GetPropertyBindingsReq, opts ...grpc.CallOption) (*GetPropertyBindingsResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetPropertyBindings(ctx, in, opts...)
}

func (m *defaultIdentity) ValidatePropertyAccess(ctx context.Context, in *ValidatePropertyAccessReq, opts ...grpc.CallOption) (*ValidatePropertyAccessResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.ValidatePropertyAccess(ctx, in, opts...)
}
