#!/bin/bash
# Build harness-pipeline.js from Markdown templates + JS loaders + core orchestration
# Run this after editing any template in .harness/agents/prompts/templates/
# or any loader in .harness/agents/prompts/*.js
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

PROMPTS_DIR="$REPO_ROOT/.harness/agents/prompts"
WORKFLOWS_DIR="$REPO_ROOT/.harness/workflows"
OUTPUT="$WORKFLOWS_DIR/harness-pipeline.js"

echo "🔨 Building harness-pipeline.js from modular sources..."

# Concatenate in order: meta first (Workflow requires it), then prompts, then core.
{
  # Meta block — must be the FIRST statement
  echo "export const meta = {"
  echo "  name: 'harness-pipeline',"
  echo "  description: 'Harness 开发管线：Generator → QA → (Debug) → Reviewer，QA FAIL 时触发根因分析，失败自动回到 Generator 修复直到 PASS',"
  echo "  phases: ["
  echo "    { title: 'Develop', detail: 'Generator 实现/修复代码' },"
  echo "    { title: 'QA', detail: 'QA Agent 编译+测试验证' },"
  echo "    { title: 'Debug', detail: '根因分析 — QA FAIL 时触发（systematic-debugging）' },"
  echo "    { title: 'Review', detail: '3 视角并行审查（安全架构/规范工程/设计业务）' },"
  echo "  ],"
  echo "}"
  echo "var SVC_DIR; // Hoisted — precede function defs that close over it"
  echo ""
  echo "// ============================================================================"
  echo "// AUTO-GENERATED by .harness/scripts/build-pipeline.sh — DO NOT EDIT DIRECTLY"
  echo "// ============================================================================"
  echo "//"
  echo "// Source architecture:"
  echo "//   📄 Markdown templates (editable, with syntax highlighting):"
  echo "//      .harness/agents/prompts/templates/generator.md"
  echo "//      .harness/agents/prompts/templates/qa.md"
  echo "//      .harness/agents/prompts/templates/review.md"
  echo "//      .harness/agents/prompts/templates/debug.md"
  echo "//"
  echo "//   🔧 Template loaders (JS logic + template rendering):"
  echo "//      .harness/agents/prompts/template-renderer.js"
  echo "//      .harness/agents/prompts/generator.js"
  echo "//      .harness/agents/prompts/qa.js"
  echo "//      .harness/agents/prompts/review.js"
  echo "//      .harness/agents/prompts/debug.js"
  echo "//"
  echo "//   🎯 Orchestration core:"
  echo "//      .harness/workflows/harness-pipeline-core.js"
  echo "//"
  echo "// Build: bash .harness/scripts/build-pipeline.sh"
  echo "// ============================================================================"
  echo ""

  # Inline template renderer (avoid external file dependency in workflow)
  cat "$PROMPTS_DIR/template-renderer.js"
  echo ""

  # Inline all 4 Markdown templates as string constants
  echo "// ============================================================================"
  echo "// Embedded Markdown Templates"
  echo "// ============================================================================"
  echo ""

  for tmpl in generator qa review debug; do
    echo "const ${tmpl}Template = \`"
    cat "$PROMPTS_DIR/templates/${tmpl}.md"
    echo "\`"
    echo ""
  done

  # Override renderFile to use embedded templates
  echo "// Override renderFile to use embedded templates instead of fs.readFileSync"
  echo "const EMBEDDED_TEMPLATES = {"
  echo "  generator: generatorTemplate,"
  echo "  qa: qaTemplate,"
  echo "  review: reviewTemplate,"
  echo "  debug: debugTemplate,"
  echo "}"
  echo ""
  echo "const originalRenderFile = renderFile"
  echo "function renderFile(templateName, context) {"
  echo "  const template = EMBEDDED_TEMPLATES[templateName]"
  echo "  if (!template) throw new Error(\`Template not found: \${templateName}\`)"
  echo "  return render(template, context)"
  echo "}"
  echo ""

  # Prompt loaders (use the -new.js versions)
  cat "$PROMPTS_DIR/generator-new.js" | grep -v "^import" | grep -v "^if (typeof module"
  echo ""
  cat "$PROMPTS_DIR/qa-new.js" | grep -v "^import" | grep -v "^if (typeof module"
  echo ""
  cat "$PROMPTS_DIR/review-new.js" | grep -v "^import" | grep -v "^if (typeof module"
  echo ""
  cat "$PROMPTS_DIR/debug-new.js" | grep -v "^import" | grep -v "^if (typeof module"
  echo ""

  # Core orchestration
  cat "$WORKFLOWS_DIR/harness-pipeline-core.js"

} > "$OUTPUT"

# Fix: const SVC_DIR → SVC_DIR (var already hoisted at top)
sed -i 's/^const SVC_DIR =/SVC_DIR =/' "$OUTPUT"

# Fix: remove duplicate meta at bottom (from harness-pipeline-core.js)
awk 'BEGIN{found=0} /^export const meta = \{/{found++; if(found>1){skip=1}} skip && /^\}/{skip=0; next} !skip' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"

# Verify syntax
if node --check "$OUTPUT" 2>&1; then
  LINES=$(wc -l < "$OUTPUT")
  TEMPLATE_LINES=$(cat "$PROMPTS_DIR/templates"/*.md | wc -l)
  echo ""
  echo "✅ harness-pipeline.js built successfully"
  echo "   📊 Total: $LINES lines"
  echo "   📄 Templates: $TEMPLATE_LINES lines (editable Markdown)"
  echo "   🎯 Logic: $((LINES - TEMPLATE_LINES)) lines (auto-generated)"
  echo ""
  echo "💡 To edit prompts:"
  echo "   Edit .harness/agents/prompts/templates/*.md (Markdown with syntax highlighting)"
  echo "   Then run: bash .harness/scripts/build-pipeline.sh"
else
  echo "❌ Syntax error in built file"
  exit 1
fi
