#!/bin/bash
# Build harness-pipeline.js from separate prompt files + core orchestration
# Run this after editing any file in .harness/agents/prompts/ or harness-pipeline-core.js
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

PROMPTS_DIR="$REPO_ROOT/.harness/agents/prompts"
WORKFLOWS_DIR="$REPO_ROOT/.harness/workflows"
OUTPUT="$WORKFLOWS_DIR/harness-pipeline.js"

# Concatenate in order: meta first (Workflow requires it), then prompts, then core.
# SVC_DIR must be hoisted with var to avoid TDZ issues with const in function closures.
{
  # Meta block — must be the FIRST statement
  echo "export const meta = {"
  echo "  name: 'harness-pipeline',"
  echo "  description: 'Harness 开发管线：Generator → QA → (Debug) → Reviewer，QA FAIL 时触发根因分析，失败自动回到 Generator 修复直到 PASS',"
  echo "  phases: ["
  echo "    { title: 'Develop', detail: 'Generator 实现/修复代码' },"
  echo "    { title: 'QA', detail: 'QA Agent 编译+测试验证' },"
  echo "    { title: 'Debug', detail: '根因分析 — QA FAIL 时触发（systematic-debugging）' },"
  echo "    { title: 'Review', detail: '3 视角并行审查（安全架构/规范工程/设计业务）' },"
  echo "  ],"
  echo "}"
  echo "var SVC_DIR; // Hoisted — precede function defs that close over it"
  echo ""
  echo "// AUTO-GENERATED by .harness/scripts/build-pipeline.sh — DO NOT EDIT DIRECTLY"
  echo "// Source files:"
  echo "//   .harness/agents/prompts/generator.js  — generatorPrompt()"
  echo "//   .harness/agents/prompts/qa.js         — QA_SCHEMA + qaPrompt()"
  echo "//   .harness/agents/prompts/review.js     — REVIEW_SCHEMA + REVIEW_LENSES + reviewLensPrompt()"
  echo "//   .harness/agents/prompts/debug.js      — DEBUG_SCHEMA + debuggingPrompt()"
  echo "//   .harness/workflows/harness-pipeline-core.js — orchestration loop"
  echo "// Build: bash .harness/scripts/build-pipeline.sh"
  echo ""
  cat "$PROMPTS_DIR/generator.js" \
      "$PROMPTS_DIR/qa.js" \
      "$PROMPTS_DIR/review.js" \
      "$PROMPTS_DIR/debug.js" \
      "$WORKFLOWS_DIR/harness-pipeline-core.js"
} > "$OUTPUT"

# Fix: const SVC_DIR → SVC_DIR (var already hoisted at top)
sed -i 's/^const SVC_DIR =/SVC_DIR =/' "$OUTPUT"

# Fix: remove duplicate meta at bottom (from harness-pipeline-core.js)
# Keep first occurrence, remove all subsequent ones
awk 'BEGIN{found=0} /^export const meta = \{/{found++; if(found>1){skip=1}} skip && /^\}/{skip=0; next} !skip' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"

# Verify syntax
if node --check "$OUTPUT" 2>&1; then
  echo "✅ harness-pipeline.js built successfully ($(wc -l < "$OUTPUT") lines)"
else
  echo "❌ Syntax error in built file"
  exit 1
fi
