// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: pb/ai_model.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiModel_ModerateText_FullMethodName  = "/ai_model.AiModel/ModerateText"
	AiModel_ModerateImage_FullMethodName = "/ai_model.AiModel/ModerateImage"
	AiModel_HealthCheck_FullMethodName   = "/ai_model.AiModel/HealthCheck"
	AiModel_GetModelInfo_FullMethodName  = "/ai_model.AiModel/GetModelInfo"
)

// AiModelClient is the client API for AiModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 模型服务
type AiModelClient interface {
	// 文本审核
	ModerateText(ctx context.Context, in *TextModerationRequest, opts ...grpc.CallOption) (*TextModerationResponse, error)
	// 图片审核（预留）
	ModerateImage(ctx context.Context, in *ImageModerationRequest, opts ...grpc.CallOption) (*ImageModerationResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 模型信息
	GetModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error)
}

type aiModelClient struct {
	cc grpc.ClientConnInterface
}

func NewAiModelClient(cc grpc.ClientConnInterface) AiModelClient {
	return &aiModelClient{cc}
}

func (c *aiModelClient) ModerateText(ctx context.Context, in *TextModerationRequest, opts ...grpc.CallOption) (*TextModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextModerationResponse)
	err := c.cc.Invoke(ctx, AiModel_ModerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) ModerateImage(ctx context.Context, in *ImageModerationRequest, opts ...grpc.CallOption) (*ImageModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageModerationResponse)
	err := c.cc.Invoke(ctx, AiModel_ModerateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AiModel_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) GetModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfoResponse)
	err := c.cc.Invoke(ctx, AiModel_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiModelServer is the server API for AiModel service.
// All implementations must embed UnimplementedAiModelServer
// for forward compatibility.
//
// AI 模型服务
type AiModelServer interface {
	// 文本审核
	ModerateText(context.Context, *TextModerationRequest) (*TextModerationResponse, error)
	// 图片审核（预留）
	ModerateImage(context.Context, *ImageModerationRequest) (*ImageModerationResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 模型信息
	GetModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error)
	mustEmbedUnimplementedAiModelServer()
}

// UnimplementedAiModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiModelServer struct{}

func (UnimplementedAiModelServer) ModerateText(context.Context, *TextModerationRequest) (*TextModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateText not implemented")
}
func (UnimplementedAiModelServer) ModerateImage(context.Context, *ImageModerationRequest) (*ImageModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateImage not implemented")
}
func (UnimplementedAiModelServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAiModelServer) GetModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedAiModelServer) mustEmbedUnimplementedAiModelServer() {}
func (UnimplementedAiModelServer) testEmbeddedByValue()                 {}

// UnsafeAiModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiModelServer will
// result in compilation errors.
type UnsafeAiModelServer interface {
	mustEmbedUnimplementedAiModelServer()
}

func RegisterAiModelServer(s grpc.ServiceRegistrar, srv AiModelServer) {
	// If the following call panics, it indicates UnimplementedAiModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiModel_ServiceDesc, srv)
}

func _AiModel_ModerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).ModerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_ModerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).ModerateText(ctx, req.(*TextModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_ModerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).ModerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_ModerateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).ModerateImage(ctx, req.(*ImageModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).GetModelInfo(ctx, req.(*ModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiModel_ServiceDesc is the grpc.ServiceDesc for AiModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_model.AiModel",
	HandlerType: (*AiModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModerateText",
			Handler:    _AiModel_ModerateText_Handler,
		},
		{
			MethodName: "ModerateImage",
			Handler:    _AiModel_ModerateImage_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AiModel_HealthCheck_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _AiModel_GetModelInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai_model.proto",
}
