// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: pb/ai_model.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiModel_CallModel_FullMethodName          = "/ai_model.AiModel/CallModel"
	AiModel_CallModelBatch_FullMethodName     = "/ai_model.AiModel/CallModelBatch"
	AiModel_GetAvailableModels_FullMethodName = "/ai_model.AiModel/GetAvailableModels"
	AiModel_HealthCheck_FullMethodName        = "/ai_model.AiModel/HealthCheck"
	AiModel_CheckModelHealth_FullMethodName   = "/ai_model.AiModel/CheckModelHealth"
	AiModel_CreateModelConfig_FullMethodName  = "/ai_model.AiModel/CreateModelConfig"
	AiModel_UpdateModelConfig_FullMethodName  = "/ai_model.AiModel/UpdateModelConfig"
	AiModel_DeleteModelConfig_FullMethodName  = "/ai_model.AiModel/DeleteModelConfig"
	AiModel_GetModelConfig_FullMethodName     = "/ai_model.AiModel/GetModelConfig"
)

// AiModelClient is the client API for AiModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 模型统一管理服务
type AiModelClient interface {
	// 通用模型调用（单次）
	CallModel(ctx context.Context, in *ModelCallRequest, opts ...grpc.CallOption) (*ModelCallResponse, error)
	// 通用模型调用（批量）
	CallModelBatch(ctx context.Context, in *ModelBatchRequest, opts ...grpc.CallOption) (*ModelBatchResponse, error)
	// 获取可用模型列表
	GetAvailableModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 单个模型健康检查
	CheckModelHealth(ctx context.Context, in *ModelHealthCheckReq, opts ...grpc.CallOption) (*ModelHealthCheckResp, error)
	// 模型配置管理
	CreateModelConfig(ctx context.Context, in *CreateModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error)
	UpdateModelConfig(ctx context.Context, in *UpdateModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error)
	DeleteModelConfig(ctx context.Context, in *DeleteModelConfigReq, opts ...grpc.CallOption) (*DeleteModelConfigResp, error)
	GetModelConfig(ctx context.Context, in *GetModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error)
}

type aiModelClient struct {
	cc grpc.ClientConnInterface
}

func NewAiModelClient(cc grpc.ClientConnInterface) AiModelClient {
	return &aiModelClient{cc}
}

func (c *aiModelClient) CallModel(ctx context.Context, in *ModelCallRequest, opts ...grpc.CallOption) (*ModelCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelCallResponse)
	err := c.cc.Invoke(ctx, AiModel_CallModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) CallModelBatch(ctx context.Context, in *ModelBatchRequest, opts ...grpc.CallOption) (*ModelBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelBatchResponse)
	err := c.cc.Invoke(ctx, AiModel_CallModelBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) GetAvailableModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelsResponse)
	err := c.cc.Invoke(ctx, AiModel_GetAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AiModel_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) CheckModelHealth(ctx context.Context, in *ModelHealthCheckReq, opts ...grpc.CallOption) (*ModelHealthCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelHealthCheckResp)
	err := c.cc.Invoke(ctx, AiModel_CheckModelHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) CreateModelConfig(ctx context.Context, in *CreateModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfigResp)
	err := c.cc.Invoke(ctx, AiModel_CreateModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) UpdateModelConfig(ctx context.Context, in *UpdateModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfigResp)
	err := c.cc.Invoke(ctx, AiModel_UpdateModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) DeleteModelConfig(ctx context.Context, in *DeleteModelConfigReq, opts ...grpc.CallOption) (*DeleteModelConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelConfigResp)
	err := c.cc.Invoke(ctx, AiModel_DeleteModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiModelClient) GetModelConfig(ctx context.Context, in *GetModelConfigReq, opts ...grpc.CallOption) (*ModelConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfigResp)
	err := c.cc.Invoke(ctx, AiModel_GetModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiModelServer is the server API for AiModel service.
// All implementations must embed UnimplementedAiModelServer
// for forward compatibility.
//
// AI 模型统一管理服务
type AiModelServer interface {
	// 通用模型调用（单次）
	CallModel(context.Context, *ModelCallRequest) (*ModelCallResponse, error)
	// 通用模型调用（批量）
	CallModelBatch(context.Context, *ModelBatchRequest) (*ModelBatchResponse, error)
	// 获取可用模型列表
	GetAvailableModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 单个模型健康检查
	CheckModelHealth(context.Context, *ModelHealthCheckReq) (*ModelHealthCheckResp, error)
	// 模型配置管理
	CreateModelConfig(context.Context, *CreateModelConfigReq) (*ModelConfigResp, error)
	UpdateModelConfig(context.Context, *UpdateModelConfigReq) (*ModelConfigResp, error)
	DeleteModelConfig(context.Context, *DeleteModelConfigReq) (*DeleteModelConfigResp, error)
	GetModelConfig(context.Context, *GetModelConfigReq) (*ModelConfigResp, error)
	mustEmbedUnimplementedAiModelServer()
}

// UnimplementedAiModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiModelServer struct{}

func (UnimplementedAiModelServer) CallModel(context.Context, *ModelCallRequest) (*ModelCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallModel not implemented")
}
func (UnimplementedAiModelServer) CallModelBatch(context.Context, *ModelBatchRequest) (*ModelBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallModelBatch not implemented")
}
func (UnimplementedAiModelServer) GetAvailableModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableModels not implemented")
}
func (UnimplementedAiModelServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAiModelServer) CheckModelHealth(context.Context, *ModelHealthCheckReq) (*ModelHealthCheckResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckModelHealth not implemented")
}
func (UnimplementedAiModelServer) CreateModelConfig(context.Context, *CreateModelConfigReq) (*ModelConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModelConfig not implemented")
}
func (UnimplementedAiModelServer) UpdateModelConfig(context.Context, *UpdateModelConfigReq) (*ModelConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModelConfig not implemented")
}
func (UnimplementedAiModelServer) DeleteModelConfig(context.Context, *DeleteModelConfigReq) (*DeleteModelConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModelConfig not implemented")
}
func (UnimplementedAiModelServer) GetModelConfig(context.Context, *GetModelConfigReq) (*ModelConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelConfig not implemented")
}
func (UnimplementedAiModelServer) mustEmbedUnimplementedAiModelServer() {}
func (UnimplementedAiModelServer) testEmbeddedByValue()                 {}

// UnsafeAiModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiModelServer will
// result in compilation errors.
type UnsafeAiModelServer interface {
	mustEmbedUnimplementedAiModelServer()
}

func RegisterAiModelServer(s grpc.ServiceRegistrar, srv AiModelServer) {
	// If the following call panics, it indicates UnimplementedAiModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiModel_ServiceDesc, srv)
}

func _AiModel_CallModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).CallModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_CallModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).CallModel(ctx, req.(*ModelCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_CallModelBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).CallModelBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_CallModelBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).CallModelBatch(ctx, req.(*ModelBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_GetAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).GetAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_GetAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).GetAvailableModels(ctx, req.(*GetModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_CheckModelHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelHealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).CheckModelHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_CheckModelHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).CheckModelHealth(ctx, req.(*ModelHealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_CreateModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).CreateModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_CreateModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).CreateModelConfig(ctx, req.(*CreateModelConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_UpdateModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).UpdateModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_UpdateModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).UpdateModelConfig(ctx, req.(*UpdateModelConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_DeleteModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).DeleteModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_DeleteModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).DeleteModelConfig(ctx, req.(*DeleteModelConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiModel_GetModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiModelServer).GetModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiModel_GetModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiModelServer).GetModelConfig(ctx, req.(*GetModelConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiModel_ServiceDesc is the grpc.ServiceDesc for AiModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_model.AiModel",
	HandlerType: (*AiModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallModel",
			Handler:    _AiModel_CallModel_Handler,
		},
		{
			MethodName: "CallModelBatch",
			Handler:    _AiModel_CallModelBatch_Handler,
		},
		{
			MethodName: "GetAvailableModels",
			Handler:    _AiModel_GetAvailableModels_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AiModel_HealthCheck_Handler,
		},
		{
			MethodName: "CheckModelHealth",
			Handler:    _AiModel_CheckModelHealth_Handler,
		},
		{
			MethodName: "CreateModelConfig",
			Handler:    _AiModel_CreateModelConfig_Handler,
		},
		{
			MethodName: "UpdateModelConfig",
			Handler:    _AiModel_UpdateModelConfig_Handler,
		},
		{
			MethodName: "DeleteModelConfig",
			Handler:    _AiModel_DeleteModelConfig_Handler,
		},
		{
			MethodName: "GetModelConfig",
			Handler:    _AiModel_GetModelConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai_model.proto",
}
