// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type APIKeyInfo struct {
	Id          int64  `json:"id"`
	ModelId     int64  `json:"model_id"`
	KeyName     string `json:"key_name"`
	Status      int64  `json:"status"`
	Description string `json:"description,omitempty"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type APIKeyResponse struct {
	BaseResponse
	Data APIKeyInfo `json:"data,omitempty"`
}

type APIKeysData struct {
	Keys  []APIKeyInfo `json:"keys"`
	Total int32        `json:"total"`
}

type APIKeysResponse struct {
	BaseResponse
	Data APIKeysData `json:"data,omitempty"`
}

type AlertConfigData struct {
	DailyLimit           float64 `json:"daily_limit"`
	MonthlyLimit         float64 `json:"monthly_limit"`
	AlertThreshold       float64 `json:"alert_threshold"`
	EnableNotification   int64   `json:"enable_notification"`
	NotificationChannels string  `json:"notification_channels"`
}

type AlertConfigResponse struct {
	BaseResponse
	Data AlertConfigData `json:"data,omitempty"`
}

type AlertRecordInfo struct {
	Id          int64   `json:"id"`
	AlertType   string  `json:"alert_type"`
	Threshold   float64 `json:"threshold"`
	ActualValue float64 `json:"actual_value"`
	Message     string  `json:"message"`
	ModelId     int64   `json:"model_id,omitempty"`
	ModelName   string  `json:"model_name,omitempty"`
	Status      string  `json:"status"`
	AlertTime   string  `json:"alert_time"`
}

type AlertRecordsData struct {
	Records []AlertRecordInfo `json:"records"`
	Total   int32             `json:"total"`
}

type AlertRecordsResponse struct {
	BaseResponse
	Data AlertRecordsData `json:"data,omitempty"`
}

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CostStatsData struct {
	TotalCost     float64            `json:"total_cost"`
	DailyCost     float64            `json:"daily_cost"`
	MonthlyCost   float64            `json:"monthly_cost"`
	ModelCosts    map[string]float64 `json:"model_costs"`
	TotalRequests int64              `json:"total_requests"`
	TotalTokens   int64              `json:"total_tokens"`
}

type CostStatsResponse struct {
	BaseResponse
	Data CostStatsData `json:"data,omitempty"`
}

type CreateAPIKeyRequest struct {
	ModelId     int64  `json:"model_id"`
	KeyName     string `json:"key_name"`
	ApiKey      string `json:"api_key"`
	Description string `json:"description,optional"`
}

type CreateModelRequest struct {
	Name                  string  `json:"name"`
	DisplayName           string  `json:"display_name"`
	Provider              string  `json:"provider"`
	Type                  string  `json:"type"`
	Endpoint              string  `json:"endpoint,optional"`
	MaxTokens             int32   `json:"max_tokens"`
	SupportedFeatures     string  `json:"supported_features"`
	CostPer1KInputTokens  float64 `json:"cost_per_1k_input_tokens"`
	CostPer1KOutputTokens float64 `json:"cost_per_1k_output_tokens"`
	Description           string  `json:"description,optional"`
}

type CreateTemplateRequest struct {
	Name        string `json:"name"`
	Content     string `json:"content"`
	Category    string `json:"category"`
	Description string `json:"description,optional"`
}

type DeleteAPIKeyRequest struct {
	Id int64 `path:"id"`
}

type DeleteModelRequest struct {
	Id int64 `path:"id"`
}

type DeleteTemplateRequest struct {
	Id int64 `path:"id"`
}

type GetAPIKeyRequest struct {
	Id int64 `path:"id"`
}

type GetCostStatsRequest struct {
	ModelId   int64  `form:"model_id,optional"`
	StartDate string `form:"start_date,optional"`
	EndDate   string `form:"end_date,optional"`
}

type GetModelRequest struct {
	Id int64 `path:"id"`
}

type GetModelsRequest struct {
	Provider string `form:"provider,optional"`
	Type     string `form:"type,optional"`
	Status   int64  `form:"status,optional"`
}

type GetModelsResponse struct {
	BaseResponse
	Data ModelsData `json:"data,omitempty"`
}

type GetTemplateRequest struct {
	Id int64 `path:"id"`
}

type GetUsageStatisticsRequest struct {
	ModelId   int64  `form:"model_id,optional"`
	StartDate string `form:"start_date,optional"`
	EndDate   string `form:"end_date,optional"`
	Page      int32  `form:"page,default=1"`
	PageSize  int32  `form:"page_size,default=10"`
}

type HealthCheckData struct {
	Status string                 `json:"status"`
	Models map[string]ModelHealth `json:"models"`
}

type HealthCheckRecord struct {
	Id           int64  `json:"id"`
	ModelId      int64  `json:"model_id"`
	Status       int64  `json:"status"`
	ResponseTime int64  `json:"response_time"`
	ErrorMessage string `json:"error_message,omitempty"`
	CheckedTime  string `json:"checked_time"`
}

type HealthCheckRecordResponse struct {
	BaseResponse
	Data HealthCheckRecord `json:"data,omitempty"`
}

type HealthCheckResponse struct {
	BaseResponse
	Data HealthCheckData `json:"data,omitempty"`
}

type ListAPIKeysRequest struct {
	ModelId int64 `form:"model_id,optional"`
	Status  int64 `form:"status,optional"`
}

type ListAlertRecordsRequest struct {
	Status    string `form:"status,optional"`
	StartDate string `form:"start_date,optional"`
	EndDate   string `form:"end_date,optional"`
}

type ListTemplatesRequest struct {
	Category string `form:"category,optional"`
	Status   int64  `form:"status,optional"`
}

type ModelBatchData struct {
	Results       []ModelCallData `json:"results"`
	TotalRequests int32           `json:"total_requests"`
	SuccessCount  int32           `json:"success_count"`
}

type ModelBatchRequest struct {
	Requests []ModelCallRequest `json:"requests"`
}

type ModelBatchResponse struct {
	BaseResponse
	Data ModelBatchData `json:"data,omitempty"`
}

type ModelCallData struct {
	Content      string  `json:"content"`
	InputTokens  int32   `json:"input_tokens"`
	OutputTokens int32   `json:"output_tokens"`
	Cost         float64 `json:"cost"`
	Latency      int64   `json:"latency"` // 毫秒
	ModelVersion string  `json:"model_version"`
}

type ModelCallRequest struct {
	ModelName    string                 `json:"model_name"`
	Prompt       string                 `json:"prompt"`
	SystemPrompt string                 `json:"system_prompt,optional"`
	MaxTokens    int32                  `json:"max_tokens,optional"`
	Temperature  float32                `json:"temperature,optional"`
	Parameters   map[string]interface{} `json:"parameters,optional"`
}

type ModelCallResponse struct {
	BaseResponse
	Data ModelCallData `json:"data,omitempty"`
}

type ModelHealth struct {
	Status       string `json:"status"`
	LastCheck    string `json:"last_check"`
	ResponseTime int64  `json:"response_time"`
	ErrorMessage string `json:"error_message,omitempty"`
}

type ModelInfo struct {
	Id                    int64   `json:"id"`
	Name                  string  `json:"name"`
	DisplayName           string  `json:"display_name"`
	Provider              string  `json:"provider"`
	Type                  string  `json:"type"`
	Endpoint              string  `json:"endpoint,omitempty"`
	MaxTokens             int32   `json:"max_tokens"`
	SupportedFeatures     string  `json:"supported_features"`
	CostPer1KInputTokens  float64 `json:"cost_per_1k_input_tokens"`
	CostPer1KOutputTokens float64 `json:"cost_per_1k_output_tokens"`
	Status                int64   `json:"status"`
	Description           string  `json:"description,omitempty"`
}

type ModelResponse struct {
	BaseResponse
	Data ModelInfo `json:"data,omitempty"`
}

type ModelsData struct {
	Models []ModelInfo `json:"models"`
	Total  int32       `json:"total"`
}

type TemplateInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Content     string `json:"content"`
	Category    string `json:"category"`
	Description string `json:"description,omitempty"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type TemplateResponse struct {
	BaseResponse
	Data TemplateInfo `json:"data,omitempty"`
}

type TemplatesData struct {
	Templates []TemplateInfo `json:"templates"`
	Total     int32          `json:"total"`
}

type TemplatesResponse struct {
	BaseResponse
	Data TemplatesData `json:"data,omitempty"`
}

type TriggerHealthCheckRequest struct {
	Id int64 `path:"id"`
}

type UpdateAPIKeyRequest struct {
	Id          int64  `json:"id"`
	KeyName     string `json:"key_name,optional"`
	ApiKey      string `json:"api_key,optional"`
	Status      int64  `json:"status,optional"`
	Description string `json:"description,optional"`
}

type UpdateAlertConfigRequest struct {
	DailyLimit           float64 `json:"daily_limit,optional"`
	MonthlyLimit         float64 `json:"monthly_limit,optional"`
	AlertThreshold       float64 `json:"alert_threshold,optional"`
	EnableNotification   int64   `json:"enable_notification,optional"`
	NotificationChannels string  `json:"notification_channels,optional"`
}

type UpdateModelRequest struct {
	Id                    int64   `json:"id"`
	DisplayName           string  `json:"display_name,optional"`
	Endpoint              string  `json:"endpoint,optional"`
	MaxTokens             int32   `json:"max_tokens,optional"`
	SupportedFeatures     string  `json:"supported_features,optional"`
	CostPer1KInputTokens  float64 `json:"cost_per_1k_input_tokens,optional"`
	CostPer1KOutputTokens float64 `json:"cost_per_1k_output_tokens,optional"`
	Status                int64   `json:"status,optional"`
	Description           string  `json:"description,optional"`
}

type UpdateTemplateRequest struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Content     string `json:"content,optional"`
	Category    string `json:"category,optional"`
	Description string `json:"description,optional"`
}

type UsageStatisticsData struct {
	Statistics []UsageStatisticsInfo `json:"statistics"`
	Total      int32                 `json:"total"`
}

type UsageStatisticsInfo struct {
	Id           int64   `json:"id"`
	ModelId      int64   `json:"model_id"`
	Date         string  `json:"date"`
	TotalCalls   int64   `json:"total_calls"`
	SuccessCalls int64   `json:"success_calls"`
	FailedCalls  int64   `json:"failed_calls"`
	TotalTokens  int64   `json:"total_tokens"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	TotalCost    float64 `json:"total_cost"`
	AvgLatency   float64 `json:"avg_latency"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type UsageStatisticsResponse struct {
	BaseResponse
	Data UsageStatisticsData `json:"data,omitempty"`
}
