// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdAdministrativeDivisionFieldNames          = builder.RawFieldNames(&MdAdministrativeDivision{})
	mdAdministrativeDivisionRows                = strings.Join(mdAdministrativeDivisionFieldNames, ",")
	mdAdministrativeDivisionRowsExpectAutoSet   = strings.Join(stringx.Remove(mdAdministrativeDivisionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdAdministrativeDivisionRowsWithPlaceHolder = strings.Join(stringx.Remove(mdAdministrativeDivisionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdAdministrativeDivisionIdPrefix   = "cache:mdAdministrativeDivision:id:"
	cacheMdAdministrativeDivisionCodePrefix = "cache:mdAdministrativeDivision:code:"
)

type (
	mdAdministrativeDivisionModel interface {
		Insert(ctx context.Context, data *MdAdministrativeDivision) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdAdministrativeDivision, error)
		FindOneByCode(ctx context.Context, code string) (*MdAdministrativeDivision, error)
		Update(ctx context.Context, data *MdAdministrativeDivision) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdAdministrativeDivisionModel struct {
		sqlc.CachedConn
		table string
	}

	MdAdministrativeDivision struct {
		Id          int64         `db:"id"`
		ParentId    sql.NullInt64 `db:"parent_id"`
		Level       int64         `db:"level"`
		Name        string        `db:"name"`
		Code        string        `db:"code"`
		Path        string        `db:"path"`
		SortOrder   int64         `db:"sort_order"`
		Status      int64         `db:"status"`
		CreatedBy   int64         `db:"created_by"`
		CreatedTime time.Time     `db:"created_time"`
		UpdatedTime time.Time     `db:"updated_time"`
		DeleteTime  sql.NullTime  `db:"delete_time"`
	}
)

func newMdAdministrativeDivisionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdAdministrativeDivisionModel {
	return &defaultMdAdministrativeDivisionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_administrative_division`",
	}
}

func (m *defaultMdAdministrativeDivisionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mdAdministrativeDivisionCodeKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionCodePrefix, data.Code)
	mdAdministrativeDivisionIdKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdAdministrativeDivisionCodeKey, mdAdministrativeDivisionIdKey)
	return err
}

func (m *defaultMdAdministrativeDivisionModel) FindOne(ctx context.Context, id int64) (*MdAdministrativeDivision, error) {
	mdAdministrativeDivisionIdKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionIdPrefix, id)
	var resp MdAdministrativeDivision
	err := m.QueryRowCtx(ctx, &resp, mdAdministrativeDivisionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdAdministrativeDivisionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdAdministrativeDivisionModel) FindOneByCode(ctx context.Context, code string) (*MdAdministrativeDivision, error) {
	mdAdministrativeDivisionCodeKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionCodePrefix, code)
	var resp MdAdministrativeDivision
	err := m.QueryRowIndexCtx(ctx, &resp, mdAdministrativeDivisionCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", mdAdministrativeDivisionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdAdministrativeDivisionModel) Insert(ctx context.Context, data *MdAdministrativeDivision) (sql.Result, error) {
	mdAdministrativeDivisionCodeKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionCodePrefix, data.Code)
	mdAdministrativeDivisionIdKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdAdministrativeDivisionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Level, data.Name, data.Code, data.Path, data.SortOrder, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, mdAdministrativeDivisionCodeKey, mdAdministrativeDivisionIdKey)
	return ret, err
}

func (m *defaultMdAdministrativeDivisionModel) Update(ctx context.Context, newData *MdAdministrativeDivision) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mdAdministrativeDivisionCodeKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionCodePrefix, data.Code)
	mdAdministrativeDivisionIdKey := fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdAdministrativeDivisionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.Level, newData.Name, newData.Code, newData.Path, newData.SortOrder, newData.Status, newData.CreatedBy, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, mdAdministrativeDivisionCodeKey, mdAdministrativeDivisionIdKey)
	return err
}

func (m *defaultMdAdministrativeDivisionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdAdministrativeDivisionIdPrefix, primary)
}

func (m *defaultMdAdministrativeDivisionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdAdministrativeDivisionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdAdministrativeDivisionModel) tableName() string {
	return m.table
}
