// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdConfigurationFieldNames          = builder.RawFieldNames(&MdConfiguration{})
	mdConfigurationRows                = strings.Join(mdConfigurationFieldNames, ",")
	mdConfigurationRowsExpectAutoSet   = strings.Join(stringx.Remove(mdConfigurationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdConfigurationRowsWithPlaceHolder = strings.Join(stringx.Remove(mdConfigurationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdConfigurationIdPrefix              = "cache:mdConfiguration:id:"
	cacheMdConfigurationModuleConfigKeyPrefix = "cache:mdConfiguration:module:configKey:"
)

type (
	mdConfigurationModel interface {
		Insert(ctx context.Context, data *MdConfiguration) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdConfiguration, error)
		FindOneByModuleConfigKey(ctx context.Context, module string, configKey string) (*MdConfiguration, error)
		Update(ctx context.Context, data *MdConfiguration) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdConfigurationModel struct {
		sqlc.CachedConn
		table string
	}

	MdConfiguration struct {
		Id               int64          `db:"id"`
		Module           string         `db:"module"`
		ConfigKey        string         `db:"config_key"`
		ConfigValue      string         `db:"config_value"`
		ValueType        string         `db:"value_type"`
		Description      sql.NullString `db:"description"`
		IsPublic         int64          `db:"is_public"`
		ApprovalStatus   int64          `db:"approval_status"`
		SubmissionStatus int64          `db:"submission_status"`
		SubmissionType   sql.NullInt64  `db:"submission_type"`
		ChangeSnapshot   sql.NullString `db:"change_snapshot"`
		SubmitterId      sql.NullInt64  `db:"submitter_id"`
		SubmitTime       sql.NullTime   `db:"submit_time"`
		ReviewerId       sql.NullInt64  `db:"reviewer_id"`
		ReviewTime       sql.NullTime   `db:"review_time"`
		ReviewNotes      sql.NullString `db:"review_notes"`
		CreatedBy        int64          `db:"created_by"`
		CreatedTime      time.Time      `db:"created_time"`
		UpdatedTime      time.Time      `db:"updated_time"`
		DeleteTime       sql.NullTime   `db:"delete_time"`
	}
)

func newMdConfigurationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdConfigurationModel {
	return &defaultMdConfigurationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_configuration`",
	}
}

func (m *defaultMdConfigurationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mdConfigurationIdKey := fmt.Sprintf("%s%v", cacheMdConfigurationIdPrefix, id)
	mdConfigurationModuleConfigKeyKey := fmt.Sprintf("%s%v:%v", cacheMdConfigurationModuleConfigKeyPrefix, data.Module, data.ConfigKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdConfigurationIdKey, mdConfigurationModuleConfigKeyKey)
	return err
}

func (m *defaultMdConfigurationModel) FindOne(ctx context.Context, id int64) (*MdConfiguration, error) {
	mdConfigurationIdKey := fmt.Sprintf("%s%v", cacheMdConfigurationIdPrefix, id)
	var resp MdConfiguration
	err := m.QueryRowCtx(ctx, &resp, mdConfigurationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdConfigurationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdConfigurationModel) FindOneByModuleConfigKey(ctx context.Context, module string, configKey string) (*MdConfiguration, error) {
	mdConfigurationModuleConfigKeyKey := fmt.Sprintf("%s%v:%v", cacheMdConfigurationModuleConfigKeyPrefix, module, configKey)
	var resp MdConfiguration
	err := m.QueryRowIndexCtx(ctx, &resp, mdConfigurationModuleConfigKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `module` = ? and `config_key` = ? limit 1", mdConfigurationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, module, configKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdConfigurationModel) Insert(ctx context.Context, data *MdConfiguration) (sql.Result, error) {
	mdConfigurationIdKey := fmt.Sprintf("%s%v", cacheMdConfigurationIdPrefix, data.Id)
	mdConfigurationModuleConfigKeyKey := fmt.Sprintf("%s%v:%v", cacheMdConfigurationModuleConfigKeyPrefix, data.Module, data.ConfigKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdConfigurationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Module, data.ConfigKey, data.ConfigValue, data.ValueType, data.Description, data.IsPublic, data.ApprovalStatus, data.SubmissionStatus, data.SubmissionType, data.ChangeSnapshot, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedBy, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, mdConfigurationIdKey, mdConfigurationModuleConfigKeyKey)
	return ret, err
}

func (m *defaultMdConfigurationModel) Update(ctx context.Context, newData *MdConfiguration) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mdConfigurationIdKey := fmt.Sprintf("%s%v", cacheMdConfigurationIdPrefix, data.Id)
	mdConfigurationModuleConfigKeyKey := fmt.Sprintf("%s%v:%v", cacheMdConfigurationModuleConfigKeyPrefix, data.Module, data.ConfigKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdConfigurationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Module, newData.ConfigKey, newData.ConfigValue, newData.ValueType, newData.Description, newData.IsPublic, newData.ApprovalStatus, newData.SubmissionStatus, newData.SubmissionType, newData.ChangeSnapshot, newData.SubmitterId, newData.SubmitTime, newData.ReviewerId, newData.ReviewTime, newData.ReviewNotes, newData.CreatedBy, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, mdConfigurationIdKey, mdConfigurationModuleConfigKeyKey)
	return err
}

func (m *defaultMdConfigurationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdConfigurationIdPrefix, primary)
}

func (m *defaultMdConfigurationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdConfigurationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdConfigurationModel) tableName() string {
	return m.table
}
