// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdCommunityFieldNames          = builder.RawFieldNames(&MdCommunity{})
	mdCommunityRows                = strings.Join(mdCommunityFieldNames, ",")
	mdCommunityRowsExpectAutoSet   = strings.Join(stringx.Remove(mdCommunityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdCommunityRowsWithPlaceHolder = strings.Join(stringx.Remove(mdCommunityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdCommunityIdPrefix = "cache:mdCommunity:id:"
)

type (
	mdCommunityModel interface {
		Insert(ctx context.Context, data *MdCommunity) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdCommunity, error)
		Update(ctx context.Context, data *MdCommunity) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdCommunityModel struct {
		sqlc.CachedConn
		table string
	}

	MdCommunity struct {
		Id               int64           `db:"id"`
		DivisionId       int64           `db:"division_id"`
		Name             string          `db:"name"`
		Address          string          `db:"address"`
		Area             sql.NullFloat64 `db:"area"`
		Population       sql.NullInt64   `db:"population"`
		CommunityType    int64           `db:"community_type"`
		SubmissionStatus int64           `db:"submission_status"`
		SubmitterId      int64           `db:"submitter_id"`
		SubmitTime       sql.NullTime    `db:"submit_time"`
		ReviewerId       sql.NullInt64   `db:"reviewer_id"`
		ReviewTime       sql.NullTime    `db:"review_time"`
		ReviewNotes      sql.NullString  `db:"review_notes"`
		CreatedTime      time.Time       `db:"created_time"`
		UpdatedTime      time.Time       `db:"updated_time"`
		DeleteTime       sql.NullTime    `db:"delete_time"`
	}
)

func newMdCommunityModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdCommunityModel {
	return &defaultMdCommunityModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_community`",
	}
}

func (m *defaultMdCommunityModel) Delete(ctx context.Context, id int64) error {
	mdCommunityIdKey := fmt.Sprintf("%s%v", cacheMdCommunityIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdCommunityIdKey)
	return err
}

func (m *defaultMdCommunityModel) FindOne(ctx context.Context, id int64) (*MdCommunity, error) {
	mdCommunityIdKey := fmt.Sprintf("%s%v", cacheMdCommunityIdPrefix, id)
	var resp MdCommunity
	err := m.QueryRowCtx(ctx, &resp, mdCommunityIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdCommunityRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdCommunityModel) Insert(ctx context.Context, data *MdCommunity) (sql.Result, error) {
	mdCommunityIdKey := fmt.Sprintf("%s%v", cacheMdCommunityIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdCommunityRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DivisionId, data.Name, data.Address, data.Area, data.Population, data.CommunityType, data.SubmissionStatus, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, mdCommunityIdKey)
	return ret, err
}

func (m *defaultMdCommunityModel) Update(ctx context.Context, data *MdCommunity) error {
	mdCommunityIdKey := fmt.Sprintf("%s%v", cacheMdCommunityIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdCommunityRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DivisionId, data.Name, data.Address, data.Area, data.Population, data.CommunityType, data.SubmissionStatus, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedTime, data.UpdatedTime, data.DeleteTime, data.Id)
	}, mdCommunityIdKey)
	return err
}

func (m *defaultMdCommunityModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdCommunityIdPrefix, primary)
}

func (m *defaultMdCommunityModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdCommunityRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdCommunityModel) tableName() string {
	return m.table
}
