// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdDistrictEconomicDataFieldNames          = builder.RawFieldNames(&MdDistrictEconomicData{})
	mdDistrictEconomicDataRows                = strings.Join(mdDistrictEconomicDataFieldNames, ",")
	mdDistrictEconomicDataRowsExpectAutoSet   = strings.Join(stringx.Remove(mdDistrictEconomicDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdDistrictEconomicDataRowsWithPlaceHolder = strings.Join(stringx.Remove(mdDistrictEconomicDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdDistrictEconomicDataIdPrefix             = "cache:mdDistrictEconomicData:id:"
	cacheMdDistrictEconomicDataDivisionIdYearPrefix = "cache:mdDistrictEconomicData:divisionId:year:"
)

type (
	mdDistrictEconomicDataModel interface {
		Insert(ctx context.Context, data *MdDistrictEconomicData) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdDistrictEconomicData, error)
		FindOneByDivisionIdYear(ctx context.Context, divisionId int64, year int64) (*MdDistrictEconomicData, error)
		Update(ctx context.Context, data *MdDistrictEconomicData) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdDistrictEconomicDataModel struct {
		sqlc.CachedConn
		table string
	}

	MdDistrictEconomicData struct {
		Id               int64           `db:"id"`
		DivisionId       int64           `db:"division_id"`
		Year             int64           `db:"year"`
		Population       sql.NullInt64   `db:"population"`
		Gdp              sql.NullFloat64 `db:"gdp"`
		PerCapitaIncome  sql.NullFloat64 `db:"per_capita_income"`
		UnemploymentRate sql.NullFloat64 `db:"unemployment_rate"`
		DataSource       sql.NullString  `db:"data_source"`
		CreatedBy        int64           `db:"created_by"`
		CreatedTime      time.Time       `db:"created_time"`
		UpdatedTime      time.Time       `db:"updated_time"`
	}
)

func newMdDistrictEconomicDataModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdDistrictEconomicDataModel {
	return &defaultMdDistrictEconomicDataModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_district_economic_data`",
	}
}

func (m *defaultMdDistrictEconomicDataModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mdDistrictEconomicDataDivisionIdYearKey := fmt.Sprintf("%s%v:%v", cacheMdDistrictEconomicDataDivisionIdYearPrefix, data.DivisionId, data.Year)
	mdDistrictEconomicDataIdKey := fmt.Sprintf("%s%v", cacheMdDistrictEconomicDataIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdDistrictEconomicDataDivisionIdYearKey, mdDistrictEconomicDataIdKey)
	return err
}

func (m *defaultMdDistrictEconomicDataModel) FindOne(ctx context.Context, id int64) (*MdDistrictEconomicData, error) {
	mdDistrictEconomicDataIdKey := fmt.Sprintf("%s%v", cacheMdDistrictEconomicDataIdPrefix, id)
	var resp MdDistrictEconomicData
	err := m.QueryRowCtx(ctx, &resp, mdDistrictEconomicDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdDistrictEconomicDataRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdDistrictEconomicDataModel) FindOneByDivisionIdYear(ctx context.Context, divisionId int64, year int64) (*MdDistrictEconomicData, error) {
	mdDistrictEconomicDataDivisionIdYearKey := fmt.Sprintf("%s%v:%v", cacheMdDistrictEconomicDataDivisionIdYearPrefix, divisionId, year)
	var resp MdDistrictEconomicData
	err := m.QueryRowIndexCtx(ctx, &resp, mdDistrictEconomicDataDivisionIdYearKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `division_id` = ? and `year` = ? limit 1", mdDistrictEconomicDataRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, divisionId, year); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdDistrictEconomicDataModel) Insert(ctx context.Context, data *MdDistrictEconomicData) (sql.Result, error) {
	mdDistrictEconomicDataDivisionIdYearKey := fmt.Sprintf("%s%v:%v", cacheMdDistrictEconomicDataDivisionIdYearPrefix, data.DivisionId, data.Year)
	mdDistrictEconomicDataIdKey := fmt.Sprintf("%s%v", cacheMdDistrictEconomicDataIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdDistrictEconomicDataRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DivisionId, data.Year, data.Population, data.Gdp, data.PerCapitaIncome, data.UnemploymentRate, data.DataSource, data.CreatedBy, data.CreatedTime, data.UpdatedTime)
	}, mdDistrictEconomicDataDivisionIdYearKey, mdDistrictEconomicDataIdKey)
	return ret, err
}

func (m *defaultMdDistrictEconomicDataModel) Update(ctx context.Context, newData *MdDistrictEconomicData) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mdDistrictEconomicDataDivisionIdYearKey := fmt.Sprintf("%s%v:%v", cacheMdDistrictEconomicDataDivisionIdYearPrefix, data.DivisionId, data.Year)
	mdDistrictEconomicDataIdKey := fmt.Sprintf("%s%v", cacheMdDistrictEconomicDataIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdDistrictEconomicDataRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DivisionId, newData.Year, newData.Population, newData.Gdp, newData.PerCapitaIncome, newData.UnemploymentRate, newData.DataSource, newData.CreatedBy, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, mdDistrictEconomicDataDivisionIdYearKey, mdDistrictEconomicDataIdKey)
	return err
}

func (m *defaultMdDistrictEconomicDataModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdDistrictEconomicDataIdPrefix, primary)
}

func (m *defaultMdDistrictEconomicDataModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdDistrictEconomicDataRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdDistrictEconomicDataModel) tableName() string {
	return m.table
}
