// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdResidentialAreaFieldNames          = builder.RawFieldNames(&MdResidentialArea{})
	mdResidentialAreaRows                = strings.Join(mdResidentialAreaFieldNames, ",")
	mdResidentialAreaRowsExpectAutoSet   = strings.Join(stringx.Remove(mdResidentialAreaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdResidentialAreaRowsWithPlaceHolder = strings.Join(stringx.Remove(mdResidentialAreaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdResidentialAreaIdPrefix = "cache:mdResidentialArea:id:"
)

type (
	mdResidentialAreaModel interface {
		Insert(ctx context.Context, data *MdResidentialArea) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdResidentialArea, error)
		Update(ctx context.Context, data *MdResidentialArea) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdResidentialAreaModel struct {
		sqlc.CachedConn
		table string
	}

	MdResidentialArea struct {
		Id               int64           `db:"id"`
		CountyId         sql.NullInt64   `db:"county_id"`
		CityId           sql.NullInt64   `db:"city_id"`
		StreetId         sql.NullInt64   `db:"street_id"`
		CommunityDivId   sql.NullInt64   `db:"community_div_id"`
		Code             sql.NullString  `db:"code"`
		Name             string          `db:"name"`
		Address          string          `db:"address"`
		Longitude        sql.NullFloat64 `db:"longitude"`
		Latitude         sql.NullFloat64 `db:"latitude"`
		DataSource       int64           `db:"data_source"`
		Area             sql.NullFloat64 `db:"area"`
		Population       sql.NullInt64   `db:"population"`
		CommunityType    int64           `db:"community_type"`
		SubmissionStatus int64           `db:"submission_status"`
		SubmissionType   sql.NullInt64   `db:"submission_type"`
		ChangeSnapshot   sql.NullString  `db:"change_snapshot"`
		SubmitterId      int64           `db:"submitter_id"`
		SubmitTime       sql.NullTime    `db:"submit_time"`
		ReviewerId       sql.NullInt64   `db:"reviewer_id"`
		ReviewTime       sql.NullTime    `db:"review_time"`
		ReviewNotes      sql.NullString  `db:"review_notes"`
		CreatedTime      time.Time       `db:"created_time"`
		UpdatedTime      time.Time       `db:"updated_time"`
		DeleteTime       sql.NullTime    `db:"delete_time"`
	}
)

func newMdResidentialAreaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdResidentialAreaModel {
	return &defaultMdResidentialAreaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_residential_area`",
	}
}

func (m *defaultMdResidentialAreaModel) Delete(ctx context.Context, id int64) error {
	mdResidentialAreaIdKey := fmt.Sprintf("%s%v", cacheMdResidentialAreaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdResidentialAreaIdKey)
	return err
}

func (m *defaultMdResidentialAreaModel) FindOne(ctx context.Context, id int64) (*MdResidentialArea, error) {
	mdResidentialAreaIdKey := fmt.Sprintf("%s%v", cacheMdResidentialAreaIdPrefix, id)
	var resp MdResidentialArea
	err := m.QueryRowCtx(ctx, &resp, mdResidentialAreaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdResidentialAreaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdResidentialAreaModel) Insert(ctx context.Context, data *MdResidentialArea) (sql.Result, error) {
	mdResidentialAreaIdKey := fmt.Sprintf("%s%v", cacheMdResidentialAreaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdResidentialAreaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CountyId, data.CityId, data.StreetId, data.CommunityDivId, data.Code, data.Name, data.Address, data.Longitude, data.Latitude, data.DataSource, data.Area, data.Population, data.CommunityType, data.SubmissionStatus, data.SubmissionType, data.ChangeSnapshot, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, mdResidentialAreaIdKey)
	return ret, err
}

func (m *defaultMdResidentialAreaModel) Update(ctx context.Context, data *MdResidentialArea) error {
	mdResidentialAreaIdKey := fmt.Sprintf("%s%v", cacheMdResidentialAreaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdResidentialAreaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CountyId, data.CityId, data.StreetId, data.CommunityDivId, data.Code, data.Name, data.Address, data.Longitude, data.Latitude, data.DataSource, data.Area, data.Population, data.CommunityType, data.SubmissionStatus, data.SubmissionType, data.ChangeSnapshot, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedTime, data.UpdatedTime, data.DeleteTime, data.Id)
	}, mdResidentialAreaIdKey)
	return err
}

func (m *defaultMdResidentialAreaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdResidentialAreaIdPrefix, primary)
}

func (m *defaultMdResidentialAreaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdResidentialAreaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdResidentialAreaModel) tableName() string {
	return m.table
}
