// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdSensitiveWordFieldNames          = builder.RawFieldNames(&MdSensitiveWord{})
	mdSensitiveWordRows                = strings.Join(mdSensitiveWordFieldNames, ",")
	mdSensitiveWordRowsExpectAutoSet   = strings.Join(stringx.Remove(mdSensitiveWordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mdSensitiveWordRowsWithPlaceHolder = strings.Join(stringx.Remove(mdSensitiveWordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMdSensitiveWordIdPrefix   = "cache:mdSensitiveWord:id:"
	cacheMdSensitiveWordWordPrefix = "cache:mdSensitiveWord:word:"
)

type (
	mdSensitiveWordModel interface {
		Insert(ctx context.Context, data *MdSensitiveWord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MdSensitiveWord, error)
		FindOneByWord(ctx context.Context, word string) (*MdSensitiveWord, error)
		Update(ctx context.Context, data *MdSensitiveWord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMdSensitiveWordModel struct {
		sqlc.CachedConn
		table string
	}

	MdSensitiveWord struct {
		Id               int64         `db:"id"`
		Word             string        `db:"word"`
		Category         string        `db:"category"`
		Severity         int64         `db:"severity"`
		Action           int64         `db:"action"`
		Status           int64         `db:"status"`
		SubmissionStatus int64         `db:"submission_status"`
		SubmissionType   sql.NullInt64 `db:"submission_type"`
		ChangeSnapshot   sql.NullString`db:"change_snapshot"`
		SubmitterId      sql.NullInt64 `db:"submitter_id"`
		SubmitTime       sql.NullTime  `db:"submit_time"`
		ReviewerId       sql.NullInt64 `db:"reviewer_id"`
		ReviewTime       sql.NullTime  `db:"review_time"`
		ReviewNotes      sql.NullString`db:"review_notes"`
		CreatedBy        int64         `db:"created_by"`
		CreatedTime      time.Time     `db:"created_time"`
		UpdatedTime      time.Time     `db:"updated_time"`
		DeleteTime       sql.NullTime  `db:"delete_time"`
	}
)

func newMdSensitiveWordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMdSensitiveWordModel {
	return &defaultMdSensitiveWordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`md_sensitive_word`",
	}
}

func (m *defaultMdSensitiveWordModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mdSensitiveWordIdKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordIdPrefix, id)
	mdSensitiveWordWordKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordWordPrefix, data.Word)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mdSensitiveWordIdKey, mdSensitiveWordWordKey)
	return err
}

func (m *defaultMdSensitiveWordModel) FindOne(ctx context.Context, id int64) (*MdSensitiveWord, error) {
	mdSensitiveWordIdKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordIdPrefix, id)
	var resp MdSensitiveWord
	err := m.QueryRowCtx(ctx, &resp, mdSensitiveWordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdSensitiveWordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdSensitiveWordModel) FindOneByWord(ctx context.Context, word string) (*MdSensitiveWord, error) {
	mdSensitiveWordWordKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordWordPrefix, word)
	var resp MdSensitiveWord
	err := m.QueryRowIndexCtx(ctx, &resp, mdSensitiveWordWordKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `word` = ? limit 1", mdSensitiveWordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, word); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdSensitiveWordModel) Insert(ctx context.Context, data *MdSensitiveWord) (sql.Result, error) {
	mdSensitiveWordIdKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordIdPrefix, data.Id)
	mdSensitiveWordWordKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordWordPrefix, data.Word)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mdSensitiveWordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Word, data.Category, data.Severity, data.Action, data.Status, data.SubmissionStatus, data.SubmissionType, data.ChangeSnapshot, data.SubmitterId, data.SubmitTime, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.CreatedBy, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, mdSensitiveWordIdKey, mdSensitiveWordWordKey)
	return ret, err
}

func (m *defaultMdSensitiveWordModel) Update(ctx context.Context, newData *MdSensitiveWord) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mdSensitiveWordIdKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordIdPrefix, data.Id)
	mdSensitiveWordWordKey := fmt.Sprintf("%s%v", cacheMdSensitiveWordWordPrefix, data.Word)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mdSensitiveWordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Word, newData.Category, newData.Severity, newData.Action, newData.Status, newData.SubmissionStatus, newData.SubmissionType, newData.ChangeSnapshot, newData.SubmitterId, newData.SubmitTime, newData.ReviewerId, newData.ReviewTime, newData.ReviewNotes, newData.CreatedBy, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, mdSensitiveWordIdKey, mdSensitiveWordWordKey)
	return err
}

func (m *defaultMdSensitiveWordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMdSensitiveWordIdPrefix, primary)
}

func (m *defaultMdSensitiveWordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mdSensitiveWordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMdSensitiveWordModel) tableName() string {
	return m.table
}
