// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	community "github.com/guxiao/community-and-home/services/masterdata/api/internal/handler/community"
	configuration "github.com/guxiao/community-and-home/services/masterdata/api/internal/handler/configuration"
	division "github.com/guxiao/community-and-home/services/masterdata/api/internal/handler/division"
	sensitiveword "github.com/guxiao/community-and-home/services/masterdata/api/internal/handler/sensitiveword"
	"github.com/guxiao/community-and-home/services/masterdata/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List communities with filters
				Method:  http.MethodGet,
				Path:    "/communities",
				Handler: community.GetCommunitiesHandler(serverCtx),
			},
			{
				// Create new community
				Method:  http.MethodPost,
				Path:    "/communities",
				Handler: community.CreateCommunityHandler(serverCtx),
			},
			{
				// Get single community details
				Method:  http.MethodGet,
				Path:    "/communities/:id",
				Handler: community.GetCommunityHandler(serverCtx),
			},
			{
				// Update community
				Method:  http.MethodPut,
				Path:    "/communities/:id",
				Handler: community.UpdateCommunityHandler(serverCtx),
			},
			{
				// Soft delete community
				Method:  http.MethodDelete,
				Path:    "/communities/:id",
				Handler: community.DeleteCommunityHandler(serverCtx),
			},
			{
				// Review community (approve/reject)
				Method:  http.MethodPost,
				Path:    "/communities/:id/review",
				Handler: community.ReviewCommunityHandler(serverCtx),
			},
			{
				// Submit community for review
				Method:  http.MethodPost,
				Path:    "/communities/:id/submit",
				Handler: community.SubmitCommunityHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/masterdata"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List or tree view of administrative divisions
				Method:  http.MethodGet,
				Path:    "/divisions",
				Handler: division.GetDivisionsHandler(serverCtx),
			},
			{
				// Create new administrative division
				Method:  http.MethodPost,
				Path:    "/divisions",
				Handler: division.CreateDivisionHandler(serverCtx),
			},
			{
				// Get single division details
				Method:  http.MethodGet,
				Path:    "/divisions/:id",
				Handler: division.GetDivisionHandler(serverCtx),
			},
			{
				// Update administrative division
				Method:  http.MethodPut,
				Path:    "/divisions/:id",
				Handler: division.UpdateDivisionHandler(serverCtx),
			},
			{
				// Soft delete administrative division
				Method:  http.MethodDelete,
				Path:    "/divisions/:id",
				Handler: division.DeleteDivisionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/masterdata"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create configuration
				Method:  http.MethodPost,
				Path:    "/configurations",
				Handler: configuration.CreateConfigHandler(serverCtx),
			},
			{
				// Get configuration list
				Method:  http.MethodGet,
				Path:    "/configurations",
				Handler: configuration.GetConfigsHandler(serverCtx),
			},
			{
				// Get single configuration
				Method:  http.MethodGet,
				Path:    "/configurations/:id",
				Handler: configuration.GetConfigHandler(serverCtx),
			},
			{
				// Update configuration
				Method:  http.MethodPut,
				Path:    "/configurations/:id",
				Handler: configuration.UpdateConfigHandler(serverCtx),
			},
			{
				// Delete configuration
				Method:  http.MethodDelete,
				Path:    "/configurations/:id",
				Handler: configuration.DeleteConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/masterdata"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create sensitive word
				Method:  http.MethodPost,
				Path:    "/sensitive-words",
				Handler: sensitiveword.CreateSensitiveWordHandler(serverCtx),
			},
			{
				// Get sensitive word list
				Method:  http.MethodGet,
				Path:    "/sensitive-words",
				Handler: sensitiveword.GetSensitiveWordsHandler(serverCtx),
			},
			{
				// Update sensitive word
				Method:  http.MethodPut,
				Path:    "/sensitive-words/:id",
				Handler: sensitiveword.UpdateSensitiveWordHandler(serverCtx),
			},
			{
				// Delete sensitive word
				Method:  http.MethodDelete,
				Path:    "/sensitive-words/:id",
				Handler: sensitiveword.DeleteSensitiveWordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/masterdata"),
	)
}
