// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: masterdata.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Masterdata_GetDivision_FullMethodName              = "/masterdata.Masterdata/GetDivision"
	Masterdata_GetDivisionsByIds_FullMethodName        = "/masterdata.Masterdata/GetDivisionsByIds"
	Masterdata_GetDivisionTree_FullMethodName          = "/masterdata.Masterdata/GetDivisionTree"
	Masterdata_GetDivisionPath_FullMethodName          = "/masterdata.Masterdata/GetDivisionPath"
	Masterdata_ValidateScope_FullMethodName            = "/masterdata.Masterdata/ValidateScope"
	Masterdata_GetCommunity_FullMethodName             = "/masterdata.Masterdata/GetCommunity"
	Masterdata_GetCommunitiesByIds_FullMethodName      = "/masterdata.Masterdata/GetCommunitiesByIds"
	Masterdata_GetCommunitiesByDivision_FullMethodName = "/masterdata.Masterdata/GetCommunitiesByDivision"
)

// MasterdataClient is the client API for Masterdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Masterdata service definition
type MasterdataClient interface {
	// Division RPC methods
	GetDivision(ctx context.Context, in *GetDivisionReq, opts ...grpc.CallOption) (*GetDivisionResp, error)
	GetDivisionsByIds(ctx context.Context, in *GetDivisionsByIdsReq, opts ...grpc.CallOption) (*GetDivisionsByIdsResp, error)
	GetDivisionTree(ctx context.Context, in *GetDivisionTreeReq, opts ...grpc.CallOption) (*GetDivisionTreeResp, error)
	GetDivisionPath(ctx context.Context, in *GetDivisionPathReq, opts ...grpc.CallOption) (*GetDivisionPathResp, error)
	ValidateScope(ctx context.Context, in *ValidateScopeReq, opts ...grpc.CallOption) (*ValidateScopeResp, error)
	// Community RPC methods
	GetCommunity(ctx context.Context, in *GetCommunityReq, opts ...grpc.CallOption) (*GetCommunityResp, error)
	GetCommunitiesByIds(ctx context.Context, in *GetCommunitiesByIdsReq, opts ...grpc.CallOption) (*GetCommunitiesByIdsResp, error)
	GetCommunitiesByDivision(ctx context.Context, in *GetCommunitiesByDivisionReq, opts ...grpc.CallOption) (*GetCommunitiesByDivisionResp, error)
}

type masterdataClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterdataClient(cc grpc.ClientConnInterface) MasterdataClient {
	return &masterdataClient{cc}
}

func (c *masterdataClient) GetDivision(ctx context.Context, in *GetDivisionReq, opts ...grpc.CallOption) (*GetDivisionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDivisionResp)
	err := c.cc.Invoke(ctx, Masterdata_GetDivision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetDivisionsByIds(ctx context.Context, in *GetDivisionsByIdsReq, opts ...grpc.CallOption) (*GetDivisionsByIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDivisionsByIdsResp)
	err := c.cc.Invoke(ctx, Masterdata_GetDivisionsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetDivisionTree(ctx context.Context, in *GetDivisionTreeReq, opts ...grpc.CallOption) (*GetDivisionTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDivisionTreeResp)
	err := c.cc.Invoke(ctx, Masterdata_GetDivisionTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetDivisionPath(ctx context.Context, in *GetDivisionPathReq, opts ...grpc.CallOption) (*GetDivisionPathResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDivisionPathResp)
	err := c.cc.Invoke(ctx, Masterdata_GetDivisionPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) ValidateScope(ctx context.Context, in *ValidateScopeReq, opts ...grpc.CallOption) (*ValidateScopeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateScopeResp)
	err := c.cc.Invoke(ctx, Masterdata_ValidateScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetCommunity(ctx context.Context, in *GetCommunityReq, opts ...grpc.CallOption) (*GetCommunityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommunityResp)
	err := c.cc.Invoke(ctx, Masterdata_GetCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetCommunitiesByIds(ctx context.Context, in *GetCommunitiesByIdsReq, opts ...grpc.CallOption) (*GetCommunitiesByIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommunitiesByIdsResp)
	err := c.cc.Invoke(ctx, Masterdata_GetCommunitiesByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterdataClient) GetCommunitiesByDivision(ctx context.Context, in *GetCommunitiesByDivisionReq, opts ...grpc.CallOption) (*GetCommunitiesByDivisionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommunitiesByDivisionResp)
	err := c.cc.Invoke(ctx, Masterdata_GetCommunitiesByDivision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterdataServer is the server API for Masterdata service.
// All implementations must embed UnimplementedMasterdataServer
// for forward compatibility.
//
// Masterdata service definition
type MasterdataServer interface {
	// Division RPC methods
	GetDivision(context.Context, *GetDivisionReq) (*GetDivisionResp, error)
	GetDivisionsByIds(context.Context, *GetDivisionsByIdsReq) (*GetDivisionsByIdsResp, error)
	GetDivisionTree(context.Context, *GetDivisionTreeReq) (*GetDivisionTreeResp, error)
	GetDivisionPath(context.Context, *GetDivisionPathReq) (*GetDivisionPathResp, error)
	ValidateScope(context.Context, *ValidateScopeReq) (*ValidateScopeResp, error)
	// Community RPC methods
	GetCommunity(context.Context, *GetCommunityReq) (*GetCommunityResp, error)
	GetCommunitiesByIds(context.Context, *GetCommunitiesByIdsReq) (*GetCommunitiesByIdsResp, error)
	GetCommunitiesByDivision(context.Context, *GetCommunitiesByDivisionReq) (*GetCommunitiesByDivisionResp, error)
	mustEmbedUnimplementedMasterdataServer()
}

// UnimplementedMasterdataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterdataServer struct{}

func (UnimplementedMasterdataServer) GetDivision(context.Context, *GetDivisionReq) (*GetDivisionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDivision not implemented")
}
func (UnimplementedMasterdataServer) GetDivisionsByIds(context.Context, *GetDivisionsByIdsReq) (*GetDivisionsByIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDivisionsByIds not implemented")
}
func (UnimplementedMasterdataServer) GetDivisionTree(context.Context, *GetDivisionTreeReq) (*GetDivisionTreeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDivisionTree not implemented")
}
func (UnimplementedMasterdataServer) GetDivisionPath(context.Context, *GetDivisionPathReq) (*GetDivisionPathResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDivisionPath not implemented")
}
func (UnimplementedMasterdataServer) ValidateScope(context.Context, *ValidateScopeReq) (*ValidateScopeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateScope not implemented")
}
func (UnimplementedMasterdataServer) GetCommunity(context.Context, *GetCommunityReq) (*GetCommunityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommunity not implemented")
}
func (UnimplementedMasterdataServer) GetCommunitiesByIds(context.Context, *GetCommunitiesByIdsReq) (*GetCommunitiesByIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommunitiesByIds not implemented")
}
func (UnimplementedMasterdataServer) GetCommunitiesByDivision(context.Context, *GetCommunitiesByDivisionReq) (*GetCommunitiesByDivisionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommunitiesByDivision not implemented")
}
func (UnimplementedMasterdataServer) mustEmbedUnimplementedMasterdataServer() {}
func (UnimplementedMasterdataServer) testEmbeddedByValue()                    {}

// UnsafeMasterdataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterdataServer will
// result in compilation errors.
type UnsafeMasterdataServer interface {
	mustEmbedUnimplementedMasterdataServer()
}

func RegisterMasterdataServer(s grpc.ServiceRegistrar, srv MasterdataServer) {
	// If the following call panics, it indicates UnimplementedMasterdataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Masterdata_ServiceDesc, srv)
}

func _Masterdata_GetDivision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDivisionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetDivision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetDivision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetDivision(ctx, req.(*GetDivisionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetDivisionsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDivisionsByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetDivisionsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetDivisionsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetDivisionsByIds(ctx, req.(*GetDivisionsByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetDivisionTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDivisionTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetDivisionTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetDivisionTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetDivisionTree(ctx, req.(*GetDivisionTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetDivisionPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDivisionPathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetDivisionPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetDivisionPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetDivisionPath(ctx, req.(*GetDivisionPathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_ValidateScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateScopeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).ValidateScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_ValidateScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).ValidateScope(ctx, req.(*ValidateScopeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommunityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetCommunity(ctx, req.(*GetCommunityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetCommunitiesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommunitiesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetCommunitiesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetCommunitiesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetCommunitiesByIds(ctx, req.(*GetCommunitiesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Masterdata_GetCommunitiesByDivision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommunitiesByDivisionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterdataServer).GetCommunitiesByDivision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Masterdata_GetCommunitiesByDivision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterdataServer).GetCommunitiesByDivision(ctx, req.(*GetCommunitiesByDivisionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Masterdata_ServiceDesc is the grpc.ServiceDesc for Masterdata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Masterdata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masterdata.Masterdata",
	HandlerType: (*MasterdataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDivision",
			Handler:    _Masterdata_GetDivision_Handler,
		},
		{
			MethodName: "GetDivisionsByIds",
			Handler:    _Masterdata_GetDivisionsByIds_Handler,
		},
		{
			MethodName: "GetDivisionTree",
			Handler:    _Masterdata_GetDivisionTree_Handler,
		},
		{
			MethodName: "GetDivisionPath",
			Handler:    _Masterdata_GetDivisionPath_Handler,
		},
		{
			MethodName: "ValidateScope",
			Handler:    _Masterdata_ValidateScope_Handler,
		},
		{
			MethodName: "GetCommunity",
			Handler:    _Masterdata_GetCommunity_Handler,
		},
		{
			MethodName: "GetCommunitiesByIds",
			Handler:    _Masterdata_GetCommunitiesByIds_Handler,
		},
		{
			MethodName: "GetCommunitiesByDivision",
			Handler:    _Masterdata_GetCommunitiesByDivision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "masterdata.proto",
}
