// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: identity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expire        int64                  `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type LoginSmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSmsReq) Reset() {
	*x = LoginSmsReq{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSmsReq) ProtoMessage() {}

func (x *LoginSmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSmsReq.ProtoReflect.Descriptor instead.
func (*LoginSmsReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *LoginSmsReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginSmsReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginSmsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expire        int64                  `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSmsResp) Reset() {
	*x = LoginSmsResp{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSmsResp) ProtoMessage() {}

func (x *LoginSmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSmsResp.ProtoReflect.Descriptor instead.
func (*LoginSmsResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *LoginSmsResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginSmsResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginSmsResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginSmsResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsReq) Reset() {
	*x = GetUsersByIdsReq{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsReq) ProtoMessage() {}

func (x *GetUsersByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsReq.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *GetUsersByIdsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsersByIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsResp) Reset() {
	*x = GetUsersByIdsResp{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsResp) ProtoMessage() {}

func (x *GetUsersByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsResp.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *GetUsersByIdsResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CheckPermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReq) Reset() {
	*x = CheckPermissionReq{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReq) ProtoMessage() {}

func (x *CheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *CheckPermissionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermissionReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResp) Reset() {
	*x = CheckPermissionResp{}
	mi := &file_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResp) ProtoMessage() {}

func (x *CheckPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResp.ProtoReflect.Descriptor instead.
func (*CheckPermissionResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{17}
}

func (x *CheckPermissionResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type GetUserPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsReq) Reset() {
	*x = GetUserPermissionsReq{}
	mi := &file_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsReq) ProtoMessage() {}

func (x *GetUserPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsReq.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserPermissionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPermissionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResp) Reset() {
	*x = GetUserPermissionsResp{}
	mi := &file_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResp) ProtoMessage() {}

func (x *GetUserPermissionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResp.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserPermissionsResp) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UserType      int32                  `protobuf:"varint,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ScopeId       int64                  `protobuf:"varint,7,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,9,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{20}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetScopeId() int64 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

func (x *User) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *User) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsSystem      int32                  `protobuf:"varint,5,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,8,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{21}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetIsSystem() int32 {
	if x != nil {
		return x.IsSystem
	}
	return 0
}

func (x *Role) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Role) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Role) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type GetRolesByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesByIdsReq) Reset() {
	*x = GetRolesByIdsReq{}
	mi := &file_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesByIdsReq) ProtoMessage() {}

func (x *GetRolesByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesByIdsReq.ProtoReflect.Descriptor instead.
func (*GetRolesByIdsReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{22}
}

func (x *GetRolesByIdsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetRolesByIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesByIdsResp) Reset() {
	*x = GetRolesByIdsResp{}
	mi := &file_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesByIdsResp) ProtoMessage() {}

func (x *GetRolesByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesByIdsResp.ProtoReflect.Descriptor instead.
func (*GetRolesByIdsResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{23}
}

func (x *GetRolesByIdsResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesReq) Reset() {
	*x = GetUserRolesReq{}
	mi := &file_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesReq) ProtoMessage() {}

func (x *GetUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesReq.ProtoReflect.Descriptor instead.
func (*GetUserRolesReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserRolesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResp) Reset() {
	*x = GetUserRolesResp{}
	mi := &file_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResp) ProtoMessage() {}

func (x *GetUserRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResp.ProtoReflect.Descriptor instead.
func (*GetUserRolesResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserRolesResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

// Verification status messages
type GetUserVerificationStatusReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyUnitId int64                  `protobuf:"varint,2,opt,name=property_unit_id,json=propertyUnitId,proto3" json:"property_unit_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserVerificationStatusReq) Reset() {
	*x = GetUserVerificationStatusReq{}
	mi := &file_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVerificationStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVerificationStatusReq) ProtoMessage() {}

func (x *GetUserVerificationStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVerificationStatusReq.ProtoReflect.Descriptor instead.
func (*GetUserVerificationStatusReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserVerificationStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserVerificationStatusReq) GetPropertyUnitId() int64 {
	if x != nil {
		return x.PropertyUnitId
	}
	return 0
}

type GetUserVerificationStatusResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VerificationId     int64                  `protobuf:"varint,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	VerificationStatus int32                  `protobuf:"varint,2,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	VerificationType   string                 `protobuf:"bytes,3,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	SubmittedTime      string                 `protobuf:"bytes,4,opt,name=submitted_time,json=submittedTime,proto3" json:"submitted_time,omitempty"`
	ReviewedTime       string                 `protobuf:"bytes,5,opt,name=reviewed_time,json=reviewedTime,proto3" json:"reviewed_time,omitempty"`
	ReviewerNotes      string                 `protobuf:"bytes,6,opt,name=reviewer_notes,json=reviewerNotes,proto3" json:"reviewer_notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserVerificationStatusResp) Reset() {
	*x = GetUserVerificationStatusResp{}
	mi := &file_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVerificationStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVerificationStatusResp) ProtoMessage() {}

func (x *GetUserVerificationStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVerificationStatusResp.ProtoReflect.Descriptor instead.
func (*GetUserVerificationStatusResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserVerificationStatusResp) GetVerificationId() int64 {
	if x != nil {
		return x.VerificationId
	}
	return 0
}

func (x *GetUserVerificationStatusResp) GetVerificationStatus() int32 {
	if x != nil {
		return x.VerificationStatus
	}
	return 0
}

func (x *GetUserVerificationStatusResp) GetVerificationType() string {
	if x != nil {
		return x.VerificationType
	}
	return ""
}

func (x *GetUserVerificationStatusResp) GetSubmittedTime() string {
	if x != nil {
		return x.SubmittedTime
	}
	return ""
}

func (x *GetUserVerificationStatusResp) GetReviewedTime() string {
	if x != nil {
		return x.ReviewedTime
	}
	return ""
}

func (x *GetUserVerificationStatusResp) GetReviewerNotes() string {
	if x != nil {
		return x.ReviewerNotes
	}
	return ""
}

// Property binding messages
type GetPropertyBindingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyBindingsReq) Reset() {
	*x = GetPropertyBindingsReq{}
	mi := &file_identity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyBindingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyBindingsReq) ProtoMessage() {}

func (x *GetPropertyBindingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyBindingsReq.ProtoReflect.Descriptor instead.
func (*GetPropertyBindingsReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{28}
}

func (x *GetPropertyBindingsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PropertyBinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyUnitId int64                  `protobuf:"varint,3,opt,name=property_unit_id,json=propertyUnitId,proto3" json:"property_unit_id,omitempty"`
	BindingType    string                 `protobuf:"bytes,4,opt,name=binding_type,json=bindingType,proto3" json:"binding_type,omitempty"`
	IsPrimary      int32                  `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	BoundTime      string                 `protobuf:"bytes,6,opt,name=bound_time,json=boundTime,proto3" json:"bound_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PropertyBinding) Reset() {
	*x = PropertyBinding{}
	mi := &file_identity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyBinding) ProtoMessage() {}

func (x *PropertyBinding) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyBinding.ProtoReflect.Descriptor instead.
func (*PropertyBinding) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{29}
}

func (x *PropertyBinding) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PropertyBinding) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PropertyBinding) GetPropertyUnitId() int64 {
	if x != nil {
		return x.PropertyUnitId
	}
	return 0
}

func (x *PropertyBinding) GetBindingType() string {
	if x != nil {
		return x.BindingType
	}
	return ""
}

func (x *PropertyBinding) GetIsPrimary() int32 {
	if x != nil {
		return x.IsPrimary
	}
	return 0
}

func (x *PropertyBinding) GetBoundTime() string {
	if x != nil {
		return x.BoundTime
	}
	return ""
}

type GetPropertyBindingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*PropertyBinding     `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyBindingsResp) Reset() {
	*x = GetPropertyBindingsResp{}
	mi := &file_identity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyBindingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyBindingsResp) ProtoMessage() {}

func (x *GetPropertyBindingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyBindingsResp.ProtoReflect.Descriptor instead.
func (*GetPropertyBindingsResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{30}
}

func (x *GetPropertyBindingsResp) GetBindings() []*PropertyBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// Property access validation messages
type ValidatePropertyAccessReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyUnitId int64                  `protobuf:"varint,2,opt,name=property_unit_id,json=propertyUnitId,proto3" json:"property_unit_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidatePropertyAccessReq) Reset() {
	*x = ValidatePropertyAccessReq{}
	mi := &file_identity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePropertyAccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePropertyAccessReq) ProtoMessage() {}

func (x *ValidatePropertyAccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePropertyAccessReq.ProtoReflect.Descriptor instead.
func (*ValidatePropertyAccessReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{31}
}

func (x *ValidatePropertyAccessReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidatePropertyAccessReq) GetPropertyUnitId() int64 {
	if x != nil {
		return x.PropertyUnitId
	}
	return 0
}

type ValidatePropertyAccessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	BindingType   string                 `protobuf:"bytes,2,opt,name=binding_type,json=bindingType,proto3" json:"binding_type,omitempty"`
	IsPrimary     int32                  `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePropertyAccessResp) Reset() {
	*x = ValidatePropertyAccessResp{}
	mi := &file_identity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePropertyAccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePropertyAccessResp) ProtoMessage() {}

func (x *ValidatePropertyAccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePropertyAccessResp.ProtoReflect.Descriptor instead.
func (*ValidatePropertyAccessResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{32}
}

func (x *ValidatePropertyAccessResp) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *ValidatePropertyAccessResp) GetBindingType() string {
	if x != nil {
		return x.BindingType
	}
	return ""
}

func (x *ValidatePropertyAccessResp) GetIsPrimary() int32 {
	if x != nil {
		return x.IsPrimary
	}
	return 0
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\bidentity\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"w\n" +
	"\tLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x16\n" +
	"\x06expire\x18\x04 \x01(\x03R\x06expire\"7\n" +
	"\vLoginSmsReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"z\n" +
	"\fLoginSmsResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x16\n" +
	"\x06expire\x18\x04 \x01(\x03R\x06expire\"g\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"U\n" +
	"\fRegisterResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire\"(\n" +
	"\x10ValidateTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"Z\n" +
	"\x11ValidateTokenResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire\"6\n" +
	"\x0fRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"e\n" +
	"\x10RefreshTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire\"!\n" +
	"\tLogoutReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"&\n" +
	"\n" +
	"LogoutResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\vGetUserResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.identity.UserR\x04user\"$\n" +
	"\x10GetUsersByIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"9\n" +
	"\x11GetUsersByIdsResp\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.identity.UserR\x05users\"a\n" +
	"\x12CheckPermissionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"/\n" +
	"\x13CheckPermissionResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"0\n" +
	"\x15GetUserPermissionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\":\n" +
	"\x16GetUserPermissionsResp\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"\xf5\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\x05R\buserType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x19\n" +
	"\bscope_id\x18\a \x01(\x03R\ascopeId\x12!\n" +
	"\fcreated_time\x18\b \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\t \x01(\tR\vupdatedTime\"\xdb\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_system\x18\x05 \x01(\x05R\bisSystem\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12!\n" +
	"\fcreated_time\x18\a \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\b \x01(\tR\vupdatedTime\"$\n" +
	"\x10GetRolesByIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"9\n" +
	"\x11GetRolesByIdsResp\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.identity.RoleR\x05roles\"*\n" +
	"\x0fGetUserRolesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"8\n" +
	"\x10GetUserRolesResp\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.identity.RoleR\x05roles\"a\n" +
	"\x1cGetUserVerificationStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x10property_unit_id\x18\x02 \x01(\x03R\x0epropertyUnitId\"\x99\x02\n" +
	"\x1dGetUserVerificationStatusResp\x12'\n" +
	"\x0fverification_id\x18\x01 \x01(\x03R\x0everificationId\x12/\n" +
	"\x13verification_status\x18\x02 \x01(\x05R\x12verificationStatus\x12+\n" +
	"\x11verification_type\x18\x03 \x01(\tR\x10verificationType\x12%\n" +
	"\x0esubmitted_time\x18\x04 \x01(\tR\rsubmittedTime\x12#\n" +
	"\rreviewed_time\x18\x05 \x01(\tR\freviewedTime\x12%\n" +
	"\x0ereviewer_notes\x18\x06 \x01(\tR\rreviewerNotes\"1\n" +
	"\x16GetPropertyBindingsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xc5\x01\n" +
	"\x0fPropertyBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12(\n" +
	"\x10property_unit_id\x18\x03 \x01(\x03R\x0epropertyUnitId\x12!\n" +
	"\fbinding_type\x18\x04 \x01(\tR\vbindingType\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x05 \x01(\x05R\tisPrimary\x12\x1d\n" +
	"\n" +
	"bound_time\x18\x06 \x01(\tR\tboundTime\"P\n" +
	"\x17GetPropertyBindingsResp\x125\n" +
	"\bbindings\x18\x01 \x03(\v2\x19.identity.PropertyBindingR\bbindings\"^\n" +
	"\x19ValidatePropertyAccessReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x10property_unit_id\x18\x02 \x01(\x03R\x0epropertyUnitId\"}\n" +
	"\x1aValidatePropertyAccessResp\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12!\n" +
	"\fbinding_type\x18\x02 \x01(\tR\vbindingType\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\x05R\tisPrimary2\xe3\b\n" +
	"\bIdentity\x120\n" +
	"\x05Login\x12\x12.identity.LoginReq\x1a\x13.identity.LoginResp\x129\n" +
	"\bLoginSms\x12\x15.identity.LoginSmsReq\x1a\x16.identity.LoginSmsResp\x129\n" +
	"\bRegister\x12\x15.identity.RegisterReq\x1a\x16.identity.RegisterResp\x12H\n" +
	"\rValidateToken\x12\x1a.identity.ValidateTokenReq\x1a\x1b.identity.ValidateTokenResp\x12E\n" +
	"\fRefreshToken\x12\x19.identity.RefreshTokenReq\x1a\x1a.identity.RefreshTokenResp\x123\n" +
	"\x06Logout\x12\x13.identity.LogoutReq\x1a\x14.identity.LogoutResp\x126\n" +
	"\aGetUser\x12\x14.identity.GetUserReq\x1a\x15.identity.GetUserResp\x12H\n" +
	"\rGetUsersByIds\x12\x1a.identity.GetUsersByIdsReq\x1a\x1b.identity.GetUsersByIdsResp\x12N\n" +
	"\x0fCheckPermission\x12\x1c.identity.CheckPermissionReq\x1a\x1d.identity.CheckPermissionResp\x12W\n" +
	"\x12GetUserPermissions\x12\x1f.identity.GetUserPermissionsReq\x1a .identity.GetUserPermissionsResp\x12H\n" +
	"\rGetRolesByIds\x12\x1a.identity.GetRolesByIdsReq\x1a\x1b.identity.GetRolesByIdsResp\x12E\n" +
	"\fGetUserRoles\x12\x19.identity.GetUserRolesReq\x1a\x1a.identity.GetUserRolesResp\x12l\n" +
	"\x19GetUserVerificationStatus\x12&.identity.GetUserVerificationStatusReq\x1a'.identity.GetUserVerificationStatusResp\x12Z\n" +
	"\x13GetPropertyBindings\x12 .identity.GetPropertyBindingsReq\x1a!.identity.GetPropertyBindingsResp\x12c\n" +
	"\x16ValidatePropertyAccess\x12#.identity.ValidatePropertyAccessReq\x1a$.identity.ValidatePropertyAccessRespB\x06Z\x04./pbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_identity_proto_goTypes = []any{
	(*LoginReq)(nil),                      // 0: identity.LoginReq
	(*LoginResp)(nil),                     // 1: identity.LoginResp
	(*LoginSmsReq)(nil),                   // 2: identity.LoginSmsReq
	(*LoginSmsResp)(nil),                  // 3: identity.LoginSmsResp
	(*RegisterReq)(nil),                   // 4: identity.RegisterReq
	(*RegisterResp)(nil),                  // 5: identity.RegisterResp
	(*ValidateTokenReq)(nil),              // 6: identity.ValidateTokenReq
	(*ValidateTokenResp)(nil),             // 7: identity.ValidateTokenResp
	(*RefreshTokenReq)(nil),               // 8: identity.RefreshTokenReq
	(*RefreshTokenResp)(nil),              // 9: identity.RefreshTokenResp
	(*LogoutReq)(nil),                     // 10: identity.LogoutReq
	(*LogoutResp)(nil),                    // 11: identity.LogoutResp
	(*GetUserReq)(nil),                    // 12: identity.GetUserReq
	(*GetUserResp)(nil),                   // 13: identity.GetUserResp
	(*GetUsersByIdsReq)(nil),              // 14: identity.GetUsersByIdsReq
	(*GetUsersByIdsResp)(nil),             // 15: identity.GetUsersByIdsResp
	(*CheckPermissionReq)(nil),            // 16: identity.CheckPermissionReq
	(*CheckPermissionResp)(nil),           // 17: identity.CheckPermissionResp
	(*GetUserPermissionsReq)(nil),         // 18: identity.GetUserPermissionsReq
	(*GetUserPermissionsResp)(nil),        // 19: identity.GetUserPermissionsResp
	(*User)(nil),                          // 20: identity.User
	(*Role)(nil),                          // 21: identity.Role
	(*GetRolesByIdsReq)(nil),              // 22: identity.GetRolesByIdsReq
	(*GetRolesByIdsResp)(nil),             // 23: identity.GetRolesByIdsResp
	(*GetUserRolesReq)(nil),               // 24: identity.GetUserRolesReq
	(*GetUserRolesResp)(nil),              // 25: identity.GetUserRolesResp
	(*GetUserVerificationStatusReq)(nil),  // 26: identity.GetUserVerificationStatusReq
	(*GetUserVerificationStatusResp)(nil), // 27: identity.GetUserVerificationStatusResp
	(*GetPropertyBindingsReq)(nil),        // 28: identity.GetPropertyBindingsReq
	(*PropertyBinding)(nil),               // 29: identity.PropertyBinding
	(*GetPropertyBindingsResp)(nil),       // 30: identity.GetPropertyBindingsResp
	(*ValidatePropertyAccessReq)(nil),     // 31: identity.ValidatePropertyAccessReq
	(*ValidatePropertyAccessResp)(nil),    // 32: identity.ValidatePropertyAccessResp
}
var file_identity_proto_depIdxs = []int32{
	20, // 0: identity.GetUserResp.user:type_name -> identity.User
	20, // 1: identity.GetUsersByIdsResp.users:type_name -> identity.User
	21, // 2: identity.GetRolesByIdsResp.roles:type_name -> identity.Role
	21, // 3: identity.GetUserRolesResp.roles:type_name -> identity.Role
	29, // 4: identity.GetPropertyBindingsResp.bindings:type_name -> identity.PropertyBinding
	0,  // 5: identity.Identity.Login:input_type -> identity.LoginReq
	2,  // 6: identity.Identity.LoginSms:input_type -> identity.LoginSmsReq
	4,  // 7: identity.Identity.Register:input_type -> identity.RegisterReq
	6,  // 8: identity.Identity.ValidateToken:input_type -> identity.ValidateTokenReq
	8,  // 9: identity.Identity.RefreshToken:input_type -> identity.RefreshTokenReq
	10, // 10: identity.Identity.Logout:input_type -> identity.LogoutReq
	12, // 11: identity.Identity.GetUser:input_type -> identity.GetUserReq
	14, // 12: identity.Identity.GetUsersByIds:input_type -> identity.GetUsersByIdsReq
	16, // 13: identity.Identity.CheckPermission:input_type -> identity.CheckPermissionReq
	18, // 14: identity.Identity.GetUserPermissions:input_type -> identity.GetUserPermissionsReq
	22, // 15: identity.Identity.GetRolesByIds:input_type -> identity.GetRolesByIdsReq
	24, // 16: identity.Identity.GetUserRoles:input_type -> identity.GetUserRolesReq
	26, // 17: identity.Identity.GetUserVerificationStatus:input_type -> identity.GetUserVerificationStatusReq
	28, // 18: identity.Identity.GetPropertyBindings:input_type -> identity.GetPropertyBindingsReq
	31, // 19: identity.Identity.ValidatePropertyAccess:input_type -> identity.ValidatePropertyAccessReq
	1,  // 20: identity.Identity.Login:output_type -> identity.LoginResp
	3,  // 21: identity.Identity.LoginSms:output_type -> identity.LoginSmsResp
	5,  // 22: identity.Identity.Register:output_type -> identity.RegisterResp
	7,  // 23: identity.Identity.ValidateToken:output_type -> identity.ValidateTokenResp
	9,  // 24: identity.Identity.RefreshToken:output_type -> identity.RefreshTokenResp
	11, // 25: identity.Identity.Logout:output_type -> identity.LogoutResp
	13, // 26: identity.Identity.GetUser:output_type -> identity.GetUserResp
	15, // 27: identity.Identity.GetUsersByIds:output_type -> identity.GetUsersByIdsResp
	17, // 28: identity.Identity.CheckPermission:output_type -> identity.CheckPermissionResp
	19, // 29: identity.Identity.GetUserPermissions:output_type -> identity.GetUserPermissionsResp
	23, // 30: identity.Identity.GetRolesByIds:output_type -> identity.GetRolesByIdsResp
	25, // 31: identity.Identity.GetUserRoles:output_type -> identity.GetUserRolesResp
	27, // 32: identity.Identity.GetUserVerificationStatus:output_type -> identity.GetUserVerificationStatusResp
	30, // 33: identity.Identity.GetPropertyBindings:output_type -> identity.GetPropertyBindingsResp
	32, // 34: identity.Identity.ValidatePropertyAccess:output_type -> identity.ValidatePropertyAccessResp
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
