// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package server

import (
	"context"

	"github.com/guxiao/community-and-home/services/identity/rpc/internal/logic"
	"github.com/guxiao/community-and-home/services/identity/rpc/internal/svc"
	"github.com/guxiao/community-and-home/services/identity/rpc/pb"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *IdentityServer) LoginSms(ctx context.Context, in *pb.LoginSmsReq) (*pb.LoginSmsResp, error) {
	l := logic.NewLoginSmsLogic(ctx, s.svcCtx)
	return l.LoginSms(in)
}

func (s *IdentityServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *IdentityServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenReq) (*pb.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *IdentityServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *IdentityServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *IdentityServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *IdentityServer) GetUsersByIds(ctx context.Context, in *pb.GetUsersByIdsReq) (*pb.GetUsersByIdsResp, error) {
	l := logic.NewGetUsersByIdsLogic(ctx, s.svcCtx)
	return l.GetUsersByIds(in)
}

func (s *IdentityServer) CheckPermission(ctx context.Context, in *pb.CheckPermissionReq) (*pb.CheckPermissionResp, error) {
	l := logic.NewCheckPermissionLogic(ctx, s.svcCtx)
	return l.CheckPermission(in)
}

func (s *IdentityServer) GetUserPermissions(ctx context.Context, in *pb.GetUserPermissionsReq) (*pb.GetUserPermissionsResp, error) {
	l := logic.NewGetUserPermissionsLogic(ctx, s.svcCtx)
	return l.GetUserPermissions(in)
}

func (s *IdentityServer) GetRolesByIds(ctx context.Context, in *pb.GetRolesByIdsReq) (*pb.GetRolesByIdsResp, error) {
	l := logic.NewGetRolesByIdsLogic(ctx, s.svcCtx)
	return l.GetRolesByIds(in)
}

func (s *IdentityServer) GetUserRoles(ctx context.Context, in *pb.GetUserRolesReq) (*pb.GetUserRolesResp, error) {
	l := logic.NewGetUserRolesLogic(ctx, s.svcCtx)
	return l.GetUserRoles(in)
}
