// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: masterdata.proto

package server

import (
	"context"

	"github.com/guxiao/community-and-home/services/masterdata/rpc/internal/logic"
	"github.com/guxiao/community-and-home/services/masterdata/rpc/internal/svc"
	"github.com/guxiao/community-and-home/services/masterdata/rpc/pb"
)

type MasterdataServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMasterdataServer
}

func NewMasterdataServer(svcCtx *svc.ServiceContext) *MasterdataServer {
	return &MasterdataServer{
		svcCtx: svcCtx,
	}
}

// Division RPC methods
func (s *MasterdataServer) GetDivision(ctx context.Context, in *pb.GetDivisionReq) (*pb.GetDivisionResp, error) {
	l := logic.NewGetDivisionLogic(ctx, s.svcCtx)
	return l.GetDivision(in)
}

func (s *MasterdataServer) GetDivisionsByIds(ctx context.Context, in *pb.GetDivisionsByIdsReq) (*pb.GetDivisionsByIdsResp, error) {
	l := logic.NewGetDivisionsByIdsLogic(ctx, s.svcCtx)
	return l.GetDivisionsByIds(in)
}

func (s *MasterdataServer) GetDivisionTree(ctx context.Context, in *pb.GetDivisionTreeReq) (*pb.GetDivisionTreeResp, error) {
	l := logic.NewGetDivisionTreeLogic(ctx, s.svcCtx)
	return l.GetDivisionTree(in)
}

func (s *MasterdataServer) GetDivisionPath(ctx context.Context, in *pb.GetDivisionPathReq) (*pb.GetDivisionPathResp, error) {
	l := logic.NewGetDivisionPathLogic(ctx, s.svcCtx)
	return l.GetDivisionPath(in)
}

func (s *MasterdataServer) ValidateScope(ctx context.Context, in *pb.ValidateScopeReq) (*pb.ValidateScopeResp, error) {
	l := logic.NewValidateScopeLogic(ctx, s.svcCtx)
	return l.ValidateScope(in)
}

// Community RPC methods
func (s *MasterdataServer) GetCommunity(ctx context.Context, in *pb.GetCommunityReq) (*pb.GetCommunityResp, error) {
	l := logic.NewGetCommunityLogic(ctx, s.svcCtx)
	return l.GetCommunity(in)
}

func (s *MasterdataServer) GetCommunitiesByIds(ctx context.Context, in *pb.GetCommunitiesByIdsReq) (*pb.GetCommunitiesByIdsResp, error) {
	l := logic.NewGetCommunitiesByIdsLogic(ctx, s.svcCtx)
	return l.GetCommunitiesByIds(in)
}

func (s *MasterdataServer) GetCommunitiesByDivision(ctx context.Context, in *pb.GetCommunitiesByDivisionReq) (*pb.GetCommunitiesByDivisionResp, error) {
	l := logic.NewGetCommunitiesByDivisionLogic(ctx, s.svcCtx)
	return l.GetCommunitiesByDivision(in)
}
