// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: masterdata.proto

package server

import (
	"context"

	"github.com/guxiao/community-and-home/services/masterdata/rpc/internal/logic"
	"github.com/guxiao/community-and-home/services/masterdata/rpc/internal/svc"
	"github.com/guxiao/community-and-home/services/masterdata/rpc/pb"
)

type MasterdataServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMasterdataServer
}

func NewMasterdataServer(svcCtx *svc.ServiceContext) *MasterdataServer {
	return &MasterdataServer{
		svcCtx: svcCtx,
	}
}

// Division RPC methods
func (s *MasterdataServer) GetDivision(ctx context.Context, in *pb.GetDivisionReq) (*pb.GetDivisionResp, error) {
	l := logic.NewGetDivisionLogic(ctx, s.svcCtx)
	return l.GetDivision(in)
}

func (s *MasterdataServer) GetDivisionsByIds(ctx context.Context, in *pb.GetDivisionsByIdsReq) (*pb.GetDivisionsByIdsResp, error) {
	l := logic.NewGetDivisionsByIdsLogic(ctx, s.svcCtx)
	return l.GetDivisionsByIds(in)
}

func (s *MasterdataServer) GetDivisionTree(ctx context.Context, in *pb.GetDivisionTreeReq) (*pb.GetDivisionTreeResp, error) {
	l := logic.NewGetDivisionTreeLogic(ctx, s.svcCtx)
	return l.GetDivisionTree(in)
}

func (s *MasterdataServer) GetDivisionPath(ctx context.Context, in *pb.GetDivisionPathReq) (*pb.GetDivisionPathResp, error) {
	l := logic.NewGetDivisionPathLogic(ctx, s.svcCtx)
	return l.GetDivisionPath(in)
}

func (s *MasterdataServer) ValidateScope(ctx context.Context, in *pb.ValidateScopeReq) (*pb.ValidateScopeResp, error) {
	l := logic.NewValidateScopeLogic(ctx, s.svcCtx)
	return l.ValidateScope(in)
}

func (s *MasterdataServer) CreateDivision(ctx context.Context, in *pb.CreateDivisionReq) (*pb.CreateDivisionResp, error) {
	l := logic.NewCreateDivisionLogic(ctx, s.svcCtx)
	return l.CreateDivision(in)
}

func (s *MasterdataServer) UpdateDivision(ctx context.Context, in *pb.UpdateDivisionReq) (*pb.UpdateDivisionResp, error) {
	l := logic.NewUpdateDivisionLogic(ctx, s.svcCtx)
	return l.UpdateDivision(in)
}

func (s *MasterdataServer) DeleteDivision(ctx context.Context, in *pb.DeleteDivisionReq) (*pb.DeleteDivisionResp, error) {
	l := logic.NewDeleteDivisionLogic(ctx, s.svcCtx)
	return l.DeleteDivision(in)
}

// Residential Area RPC methods
func (s *MasterdataServer) GetResidentialArea(ctx context.Context, in *pb.GetResidentialAreaReq) (*pb.GetResidentialAreaResp, error) {
	l := logic.NewGetResidentialAreaLogic(ctx, s.svcCtx)
	return l.GetResidentialArea(in)
}

func (s *MasterdataServer) GetResidentialAreasByIds(ctx context.Context, in *pb.GetResidentialAreasByIdsReq) (*pb.GetResidentialAreasByIdsResp, error) {
	l := logic.NewGetResidentialAreasByIdsLogic(ctx, s.svcCtx)
	return l.GetResidentialAreasByIds(in)
}

func (s *MasterdataServer) GetResidentialAreasByDivision(ctx context.Context, in *pb.GetResidentialAreasByDivisionReq) (*pb.GetResidentialAreasByDivisionResp, error) {
	l := logic.NewGetResidentialAreasByDivisionLogic(ctx, s.svcCtx)
	return l.GetResidentialAreasByDivision(in)
}
