// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai_model.proto

package server

import (
	"context"

	"github.com/guxiao/community-and-home/services/ai-model/rpc/internal/logic"
	"github.com/guxiao/community-and-home/services/ai-model/rpc/internal/svc"
	"github.com/guxiao/community-and-home/services/ai-model/rpc/pb"
)

type AiModelServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiModelServer
}

func NewAiModelServer(svcCtx *svc.ServiceContext) *AiModelServer {
	return &AiModelServer{
		svcCtx: svcCtx,
	}
}

// 通用模型调用（单次）
func (s *AiModelServer) CallModel(ctx context.Context, in *pb.ModelCallRequest) (*pb.ModelCallResponse, error) {
	l := logic.NewCallModelLogic(ctx, s.svcCtx)
	return l.CallModel(in)
}

// 通用模型调用（批量）
func (s *AiModelServer) CallModelBatch(ctx context.Context, in *pb.ModelBatchRequest) (*pb.ModelBatchResponse, error) {
	l := logic.NewCallModelBatchLogic(ctx, s.svcCtx)
	return l.CallModelBatch(in)
}

// 获取可用模型列表
func (s *AiModelServer) GetAvailableModels(ctx context.Context, in *pb.GetModelsRequest) (*pb.GetModelsResponse, error) {
	l := logic.NewGetAvailableModelsLogic(ctx, s.svcCtx)
	return l.GetAvailableModels(in)
}

// 健康检查
func (s *AiModelServer) HealthCheck(ctx context.Context, in *pb.HealthCheckRequest) (*pb.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}

// 单个模型健康检查
func (s *AiModelServer) CheckModelHealth(ctx context.Context, in *pb.ModelHealthCheckReq) (*pb.ModelHealthCheckResp, error) {
	l := logic.NewCheckModelHealthLogic(ctx, s.svcCtx)
	return l.CheckModelHealth(in)
}

// 模型配置管理
func (s *AiModelServer) CreateModelConfig(ctx context.Context, in *pb.CreateModelConfigReq) (*pb.ModelConfigResp, error) {
	l := logic.NewCreateModelConfigLogic(ctx, s.svcCtx)
	return l.CreateModelConfig(in)
}

func (s *AiModelServer) UpdateModelConfig(ctx context.Context, in *pb.UpdateModelConfigReq) (*pb.ModelConfigResp, error) {
	l := logic.NewUpdateModelConfigLogic(ctx, s.svcCtx)
	return l.UpdateModelConfig(in)
}

func (s *AiModelServer) DeleteModelConfig(ctx context.Context, in *pb.DeleteModelConfigReq) (*pb.DeleteModelConfigResp, error) {
	l := logic.NewDeleteModelConfigLogic(ctx, s.svcCtx)
	return l.DeleteModelConfig(in)
}

func (s *AiModelServer) GetModelConfig(ctx context.Context, in *pb.GetModelConfigReq) (*pb.ModelConfigResp, error) {
	l := logic.NewGetModelConfigLogic(ctx, s.svcCtx)
	return l.GetModelConfig(in)
}
