// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amAlertRecordFieldNames          = builder.RawFieldNames(&AmAlertRecord{})
	amAlertRecordRows                = strings.Join(amAlertRecordFieldNames, ",")
	amAlertRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(amAlertRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amAlertRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(amAlertRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmAlertRecordIdPrefix = "cache:aiModelDb:amAlertRecord:id:"
)

type (
	amAlertRecordModel interface {
		Insert(ctx context.Context, data *AmAlertRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmAlertRecord, error)
		Update(ctx context.Context, data *AmAlertRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmAlertRecordModel struct {
		sqlc.CachedConn
		table string
	}

	AmAlertRecord struct {
		Id           int64          `db:"id"`
		AlertType    string         `db:"alert_type"`    // é¢„è­¦ç±»åž‹ï¼šdaily/monthly/quota
		Threshold    float64        `db:"threshold"`     // é˜ˆå€¼
		ActualValue  float64        `db:"actual_value"`  // å®žé™…å€¼
		Message      sql.NullString `db:"message"`       // é¢„è­¦æ¶ˆæ¯
		ModelId      sql.NullInt64  `db:"model_id"`      // å…³è”çš„æ¨¡åž‹IDï¼ˆå¯é€‰ï¼‰
		ModelName    sql.NullString `db:"model_name"`    // æ¨¡åž‹åç§°
		Status       string         `db:"status"`        // çŠ¶æ€ï¼špending/notified/resolved
		NotifiedTime sql.NullTime   `db:"notified_time"` // é€šçŸ¥æ—¶é—´
		ResolvedTime sql.NullTime   `db:"resolved_time"` // è§£å†³æ—¶é—´
		AlertTime    time.Time      `db:"alert_time"`
	}
)

func newAmAlertRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmAlertRecordModel {
	return &defaultAmAlertRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_alert_record`",
	}
}

func (m *defaultAmAlertRecordModel) Delete(ctx context.Context, id int64) error {
	aiModelDbAmAlertRecordIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmAlertRecordIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmAlertRecordIdKey)
	return err
}

func (m *defaultAmAlertRecordModel) FindOne(ctx context.Context, id int64) (*AmAlertRecord, error) {
	aiModelDbAmAlertRecordIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmAlertRecordIdPrefix, id)
	var resp AmAlertRecord
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmAlertRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amAlertRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmAlertRecordModel) Insert(ctx context.Context, data *AmAlertRecord) (sql.Result, error) {
	aiModelDbAmAlertRecordIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmAlertRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amAlertRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AlertType, data.Threshold, data.ActualValue, data.Message, data.ModelId, data.ModelName, data.Status, data.NotifiedTime, data.ResolvedTime, data.AlertTime)
	}, aiModelDbAmAlertRecordIdKey)
	return ret, err
}

func (m *defaultAmAlertRecordModel) Update(ctx context.Context, data *AmAlertRecord) error {
	aiModelDbAmAlertRecordIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmAlertRecordIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amAlertRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AlertType, data.Threshold, data.ActualValue, data.Message, data.ModelId, data.ModelName, data.Status, data.NotifiedTime, data.ResolvedTime, data.AlertTime, data.Id)
	}, aiModelDbAmAlertRecordIdKey)
	return err
}

func (m *defaultAmAlertRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmAlertRecordIdPrefix, primary)
}

func (m *defaultAmAlertRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amAlertRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmAlertRecordModel) tableName() string {
	return m.table
}
