// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amApiKeyFieldNames          = builder.RawFieldNames(&AmApiKey{})
	amApiKeyRows                = strings.Join(amApiKeyFieldNames, ",")
	amApiKeyRowsExpectAutoSet   = strings.Join(stringx.Remove(amApiKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amApiKeyRowsWithPlaceHolder = strings.Join(stringx.Remove(amApiKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmApiKeyIdPrefix = "cache:aiModelDb:amApiKey:id:"
)

type (
	amApiKeyModel interface {
		Insert(ctx context.Context, data *AmApiKey) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmApiKey, error)
		Update(ctx context.Context, data *AmApiKey) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmApiKeyModel struct {
		sqlc.CachedConn
		table string
	}

	AmApiKey struct {
		Id              int64          `db:"id"`
		ModelId         int64          `db:"model_id"`          // å…³è”çš„æ¨¡åž‹é…ç½®ID
		KeyName         string         `db:"key_name"`          // å¯†é’¥åç§°
		Provider        string         `db:"provider"`          // æä¾›å•†ï¼šclaude/openai/ollama
		ApiKey          string         `db:"api_key"`           // APIå¯†é’¥ï¼ˆAESåŠ å¯†å­˜å‚¨ï¼‰
		MaskedKey       sql.NullString `db:"masked_key"`        // è„±æ•æ˜¾ç¤ºï¼šsk-ant-***abc123
		DailyQuota      int64          `db:"daily_quota"`       // æ¯æ—¥é…é¢ï¼ˆ0=æ— é™åˆ¶ï¼‰
		MonthlyQuota    int64          `db:"monthly_quota"`     // æ¯æœˆé…é¢ï¼ˆ0=æ— é™åˆ¶ï¼‰
		Priority        int64          `db:"priority"`          // ä¼˜å…ˆçº§ï¼šæ•°å­—è¶Šå°ä¼˜å…ˆçº§è¶Šé«˜
		Status          int64          `db:"status"`            // çŠ¶æ€ï¼š1=å¯ç”¨ï¼Œ0=ç¦ç”¨
		FailureCount    int64          `db:"failure_count"`     // è¿žç»­å¤±è´¥æ¬¡æ•°
		LastUsedTime    sql.NullTime   `db:"last_used_time"`    // æœ€åŽä½¿ç”¨æ—¶é—´
		LastFailureTime sql.NullTime   `db:"last_failure_time"` // æœ€åŽå¤±è´¥æ—¶é—´
		CreatedTime     time.Time      `db:"created_time"`
		UpdatedTime     time.Time      `db:"updated_time"`
		DeleteTime      sql.NullTime   `db:"delete_time"`
	}
)

func newAmApiKeyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmApiKeyModel {
	return &defaultAmApiKeyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_api_key`",
	}
}

func (m *defaultAmApiKeyModel) Delete(ctx context.Context, id int64) error {
	aiModelDbAmApiKeyIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmApiKeyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmApiKeyIdKey)
	return err
}

func (m *defaultAmApiKeyModel) FindOne(ctx context.Context, id int64) (*AmApiKey, error) {
	aiModelDbAmApiKeyIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmApiKeyIdPrefix, id)
	var resp AmApiKey
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmApiKeyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amApiKeyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmApiKeyModel) Insert(ctx context.Context, data *AmApiKey) (sql.Result, error) {
	aiModelDbAmApiKeyIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmApiKeyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amApiKeyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModelId, data.KeyName, data.Provider, data.ApiKey, data.MaskedKey, data.DailyQuota, data.MonthlyQuota, data.Priority, data.Status, data.FailureCount, data.LastUsedTime, data.LastFailureTime, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, aiModelDbAmApiKeyIdKey)
	return ret, err
}

func (m *defaultAmApiKeyModel) Update(ctx context.Context, data *AmApiKey) error {
	aiModelDbAmApiKeyIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmApiKeyIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amApiKeyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ModelId, data.KeyName, data.Provider, data.ApiKey, data.MaskedKey, data.DailyQuota, data.MonthlyQuota, data.Priority, data.Status, data.FailureCount, data.LastUsedTime, data.LastFailureTime, data.CreatedTime, data.UpdatedTime, data.DeleteTime, data.Id)
	}, aiModelDbAmApiKeyIdKey)
	return err
}

func (m *defaultAmApiKeyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmApiKeyIdPrefix, primary)
}

func (m *defaultAmApiKeyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amApiKeyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmApiKeyModel) tableName() string {
	return m.table
}
