// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amCallLogFieldNames          = builder.RawFieldNames(&AmCallLog{})
	amCallLogRows                = strings.Join(amCallLogFieldNames, ",")
	amCallLogRowsExpectAutoSet   = strings.Join(stringx.Remove(amCallLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amCallLogRowsWithPlaceHolder = strings.Join(stringx.Remove(amCallLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmCallLogIdPrefix = "cache:aiModelDb:amCallLog:id:"
)

type (
	amCallLogModel interface {
		Insert(ctx context.Context, data *AmCallLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmCallLog, error)
		Update(ctx context.Context, data *AmCallLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmCallLogModel struct {
		sqlc.CachedConn
		table string
	}

	AmCallLog struct {
		Id            int64          `db:"id"`
		RequestId     sql.NullString `db:"request_id"`     // è¯·æ±‚IDï¼ˆç”¨äºŽè¿½è¸ªï¼‰
		ModelId       int64          `db:"model_id"`       // æ¨¡åž‹é…ç½®ID
		ModelName     string         `db:"model_name"`     // æ¨¡åž‹åç§°
		CallerService sql.NullString `db:"caller_service"` // è°ƒç”¨æ–¹æœåŠ¡å
		Method        sql.NullString `db:"method"`         // è°ƒç”¨æ–¹æ³•ï¼šCallModel/CallModelBatch
		PromptLength  sql.NullInt64  `db:"prompt_length"`  // æç¤ºè¯é•¿åº¦
		InputTokens   int64          `db:"input_tokens"`
		OutputTokens  int64          `db:"output_tokens"`
		TotalTokens   int64          `db:"total_tokens"`
		Cost          float64        `db:"cost"`       // æœ¬æ¬¡è°ƒç”¨æˆæœ¬(USD)
		LatencyMs     sql.NullInt64  `db:"latency_ms"` // è€—æ—¶(ms)
		Success       int64          `db:"success"`    // æ˜¯å¦æˆåŠŸï¼š1=æˆåŠŸï¼Œ0=å¤±è´¥
		ErrorCode     sql.NullString `db:"error_code"` // é”™è¯¯ç 
		ErrorMsg      sql.NullString `db:"error_msg"`  // é”™è¯¯ä¿¡æ¯
		CreatedTime   time.Time      `db:"created_time"`
	}
)

func newAmCallLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmCallLogModel {
	return &defaultAmCallLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_call_log`",
	}
}

func (m *defaultAmCallLogModel) Delete(ctx context.Context, id int64) error {
	aiModelDbAmCallLogIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmCallLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmCallLogIdKey)
	return err
}

func (m *defaultAmCallLogModel) FindOne(ctx context.Context, id int64) (*AmCallLog, error) {
	aiModelDbAmCallLogIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmCallLogIdPrefix, id)
	var resp AmCallLog
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmCallLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amCallLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmCallLogModel) Insert(ctx context.Context, data *AmCallLog) (sql.Result, error) {
	aiModelDbAmCallLogIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmCallLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amCallLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RequestId, data.ModelId, data.ModelName, data.CallerService, data.Method, data.PromptLength, data.InputTokens, data.OutputTokens, data.TotalTokens, data.Cost, data.LatencyMs, data.Success, data.ErrorCode, data.ErrorMsg, data.CreatedTime)
	}, aiModelDbAmCallLogIdKey)
	return ret, err
}

func (m *defaultAmCallLogModel) Update(ctx context.Context, data *AmCallLog) error {
	aiModelDbAmCallLogIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmCallLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amCallLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RequestId, data.ModelId, data.ModelName, data.CallerService, data.Method, data.PromptLength, data.InputTokens, data.OutputTokens, data.TotalTokens, data.Cost, data.LatencyMs, data.Success, data.ErrorCode, data.ErrorMsg, data.CreatedTime, data.Id)
	}, aiModelDbAmCallLogIdKey)
	return err
}

func (m *defaultAmCallLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmCallLogIdPrefix, primary)
}

func (m *defaultAmCallLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amCallLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmCallLogModel) tableName() string {
	return m.table
}
