// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amHealthCheckFieldNames          = builder.RawFieldNames(&AmHealthCheck{})
	amHealthCheckRows                = strings.Join(amHealthCheckFieldNames, ",")
	amHealthCheckRowsExpectAutoSet   = strings.Join(stringx.Remove(amHealthCheckFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amHealthCheckRowsWithPlaceHolder = strings.Join(stringx.Remove(amHealthCheckFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmHealthCheckIdPrefix = "cache:aiModelDb:amHealthCheck:id:"
)

type (
	amHealthCheckModel interface {
		Insert(ctx context.Context, data *AmHealthCheck) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmHealthCheck, error)
		Update(ctx context.Context, data *AmHealthCheck) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmHealthCheckModel struct {
		sqlc.CachedConn
		table string
	}

	AmHealthCheck struct {
		Id        int64          `db:"id"`
		ModelId   int64          `db:"model_id"`   // æ¨¡åž‹é…ç½®ID
		ModelName string         `db:"model_name"` // æ¨¡åž‹åç§°
		Status    string         `db:"status"`     // healthy/degraded/unhealthy
		LatencyMs sql.NullInt64  `db:"latency_ms"` // å“åº”æ—¶é—´(ms)
		ErrorMsg  sql.NullString `db:"error_msg"`  // é”™è¯¯ä¿¡æ¯
		CheckTime time.Time      `db:"check_time"`
	}
)

func newAmHealthCheckModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmHealthCheckModel {
	return &defaultAmHealthCheckModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_health_check`",
	}
}

func (m *defaultAmHealthCheckModel) Delete(ctx context.Context, id int64) error {
	aiModelDbAmHealthCheckIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmHealthCheckIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmHealthCheckIdKey)
	return err
}

func (m *defaultAmHealthCheckModel) FindOne(ctx context.Context, id int64) (*AmHealthCheck, error) {
	aiModelDbAmHealthCheckIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmHealthCheckIdPrefix, id)
	var resp AmHealthCheck
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmHealthCheckIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amHealthCheckRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmHealthCheckModel) Insert(ctx context.Context, data *AmHealthCheck) (sql.Result, error) {
	aiModelDbAmHealthCheckIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmHealthCheckIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, amHealthCheckRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModelId, data.ModelName, data.Status, data.LatencyMs, data.ErrorMsg, data.CheckTime)
	}, aiModelDbAmHealthCheckIdKey)
	return ret, err
}

func (m *defaultAmHealthCheckModel) Update(ctx context.Context, data *AmHealthCheck) error {
	aiModelDbAmHealthCheckIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmHealthCheckIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amHealthCheckRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ModelId, data.ModelName, data.Status, data.LatencyMs, data.ErrorMsg, data.CheckTime, data.Id)
	}, aiModelDbAmHealthCheckIdKey)
	return err
}

func (m *defaultAmHealthCheckModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmHealthCheckIdPrefix, primary)
}

func (m *defaultAmHealthCheckModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amHealthCheckRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmHealthCheckModel) tableName() string {
	return m.table
}
