// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amModelConfigFieldNames          = builder.RawFieldNames(&AmModelConfig{})
	amModelConfigRows                = strings.Join(amModelConfigFieldNames, ",")
	amModelConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(amModelConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amModelConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(amModelConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmModelConfigIdPrefix        = "cache:aiModelDb:amModelConfig:id:"
	cacheAiModelDbAmModelConfigModelNamePrefix = "cache:aiModelDb:amModelConfig:modelName:"
)

type (
	amModelConfigModel interface {
		Insert(ctx context.Context, data *AmModelConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmModelConfig, error)
		FindOneByModelName(ctx context.Context, modelName string) (*AmModelConfig, error)
		Update(ctx context.Context, data *AmModelConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmModelConfigModel struct {
		sqlc.CachedConn
		table string
	}

	AmModelConfig struct {
		Id                    int64          `db:"id"`
		ModelName             string         `db:"model_name"`                // æ¨¡åž‹æ ‡è¯†ï¼šclaude-opus-4/gpt-4/qwen
		ModelType             string         `db:"model_type"`                // æ¨¡åž‹ç±»åž‹ï¼šcloud/local
		Provider              string         `db:"provider"`                  // æä¾›å•†ï¼šclaude/openai/ollama
		DisplayName           sql.NullString `db:"display_name"`              // æ˜¾ç¤ºåç§°
		Description           sql.NullString `db:"description"`               // æ¨¡åž‹æè¿°
		Capabilities          sql.NullString `db:"capabilities"`              // èƒ½åŠ›åˆ—è¡¨ï¼š["text_generation","classification"]
		Endpoint              sql.NullString `db:"endpoint"`                  // APIç«¯ç‚¹
		ApiKeyId              sql.NullInt64  `db:"api_key_id"`                // å…³è”çš„API Key IDï¼ˆå¤–éƒ¨æ¨¡åž‹ï¼‰
		Timeout               int64          `db:"timeout"`                   // è¶…æ—¶æ—¶é—´(ms)
		MaxRetries            int64          `db:"max_retries"`               // æœ€å¤§é‡è¯•æ¬¡æ•°
		CostPer1KInputTokens  float64        `db:"cost_per_1k_input_tokens"`  // æ¯1Kè¾“å…¥tokenæˆæœ¬(USD)
		CostPer1KOutputTokens float64        `db:"cost_per_1k_output_tokens"` // æ¯1Kè¾“å‡ºtokenæˆæœ¬(USD)
		Priority              int64          `db:"priority"`                  // ä¼˜å…ˆçº§ï¼šæ•°å­—è¶Šå°ä¼˜å…ˆçº§è¶Šé«˜
		DailyQuota            int64          `db:"daily_quota"`               // æ¯æ—¥è°ƒç”¨é…é¢ï¼ˆ0=ä¸é™åˆ¶ï¼‰
		MonthlyQuota          int64          `db:"monthly_quota"`             // æ¯æœˆè°ƒç”¨é…é¢ï¼ˆ0=ä¸é™åˆ¶ï¼‰
		Status                int64          `db:"status"`                    // çŠ¶æ€ï¼š1=å¯ç”¨ï¼Œ0=ç¦ç”¨
		HealthStatus          string         `db:"health_status"`             // å¥åº·çŠ¶æ€ï¼šhealthy/degraded/unhealthy/unknown
		LastHealthCheck       sql.NullTime   `db:"last_health_check"`         // æœ€åŽå¥åº·æ£€æŸ¥æ—¶é—´
		CreatedTime           time.Time      `db:"created_time"`
		UpdatedTime           time.Time      `db:"updated_time"`
		DeleteTime            sql.NullTime   `db:"delete_time"`
	}
)

func newAmModelConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmModelConfigModel {
	return &defaultAmModelConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_model_config`",
	}
}

func (m *defaultAmModelConfigModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aiModelDbAmModelConfigIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigIdPrefix, id)
	aiModelDbAmModelConfigModelNameKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigModelNamePrefix, data.ModelName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmModelConfigIdKey, aiModelDbAmModelConfigModelNameKey)
	return err
}

func (m *defaultAmModelConfigModel) FindOne(ctx context.Context, id int64) (*AmModelConfig, error) {
	aiModelDbAmModelConfigIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigIdPrefix, id)
	var resp AmModelConfig
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmModelConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amModelConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmModelConfigModel) FindOneByModelName(ctx context.Context, modelName string) (*AmModelConfig, error) {
	aiModelDbAmModelConfigModelNameKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigModelNamePrefix, modelName)
	var resp AmModelConfig
	err := m.QueryRowIndexCtx(ctx, &resp, aiModelDbAmModelConfigModelNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `model_name` = ? limit 1", amModelConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, modelName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmModelConfigModel) Insert(ctx context.Context, data *AmModelConfig) (sql.Result, error) {
	aiModelDbAmModelConfigIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigIdPrefix, data.Id)
	aiModelDbAmModelConfigModelNameKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigModelNamePrefix, data.ModelName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amModelConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModelName, data.ModelType, data.Provider, data.DisplayName, data.Description, data.Capabilities, data.Endpoint, data.ApiKeyId, data.Timeout, data.MaxRetries, data.CostPer1KInputTokens, data.CostPer1KOutputTokens, data.Priority, data.DailyQuota, data.MonthlyQuota, data.Status, data.HealthStatus, data.LastHealthCheck, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, aiModelDbAmModelConfigIdKey, aiModelDbAmModelConfigModelNameKey)
	return ret, err
}

func (m *defaultAmModelConfigModel) Update(ctx context.Context, newData *AmModelConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aiModelDbAmModelConfigIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigIdPrefix, data.Id)
	aiModelDbAmModelConfigModelNameKey := fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigModelNamePrefix, data.ModelName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amModelConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ModelName, newData.ModelType, newData.Provider, newData.DisplayName, newData.Description, newData.Capabilities, newData.Endpoint, newData.ApiKeyId, newData.Timeout, newData.MaxRetries, newData.CostPer1KInputTokens, newData.CostPer1KOutputTokens, newData.Priority, newData.DailyQuota, newData.MonthlyQuota, newData.Status, newData.HealthStatus, newData.LastHealthCheck, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, aiModelDbAmModelConfigIdKey, aiModelDbAmModelConfigModelNameKey)
	return err
}

func (m *defaultAmModelConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmModelConfigIdPrefix, primary)
}

func (m *defaultAmModelConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amModelConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmModelConfigModel) tableName() string {
	return m.table
}
