// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amPromptTemplateFieldNames          = builder.RawFieldNames(&AmPromptTemplate{})
	amPromptTemplateRows                = strings.Join(amPromptTemplateFieldNames, ",")
	amPromptTemplateRowsExpectAutoSet   = strings.Join(stringx.Remove(amPromptTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amPromptTemplateRowsWithPlaceHolder = strings.Join(stringx.Remove(amPromptTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiModelDbAmPromptTemplateIdPrefix         = "cache:aiModelDb:amPromptTemplate:id:"
	cacheAiModelDbAmPromptTemplateTemplateIdPrefix = "cache:aiModelDb:amPromptTemplate:templateId:"
)

type (
	amPromptTemplateModel interface {
		Insert(ctx context.Context, data *AmPromptTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmPromptTemplate, error)
		FindOneByTemplateId(ctx context.Context, templateId string) (*AmPromptTemplate, error)
		Update(ctx context.Context, data *AmPromptTemplate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmPromptTemplateModel struct {
		sqlc.CachedConn
		table string
	}

	AmPromptTemplate struct {
		Id           int64          `db:"id"`
		TemplateId   string         `db:"template_id"`   // æ¨¡æ¿ID
		TemplateName string         `db:"template_name"` // æ¨¡æ¿åç§°
		Category     sql.NullString `db:"category"`      // åˆ†ç±»ï¼šclassification/moderation/qa
		Content      string         `db:"content"`       // æ¨¡æ¿å†…å®¹ï¼Œæ”¯æŒ{{variable}}å˜é‡
		Variables    sql.NullString `db:"variables"`     // å˜é‡åˆ—è¡¨ï¼š["words","categories"]
		Version      string         `db:"version"`
		IsActive     int64          `db:"is_active"`   // æ˜¯å¦æ¿€æ´»ï¼š1=æ¿€æ´»ï¼Œ0=æœªæ¿€æ´»
		UsageCount   int64          `db:"usage_count"` // ä½¿ç”¨æ¬¡æ•°
		Description  sql.NullString `db:"description"` // æ¨¡æ¿è¯´æ˜Ž
		CreatedTime  time.Time      `db:"created_time"`
		UpdatedTime  time.Time      `db:"updated_time"`
		DeleteTime   sql.NullTime   `db:"delete_time"`
	}
)

func newAmPromptTemplateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmPromptTemplateModel {
	return &defaultAmPromptTemplateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_prompt_template`",
	}
}

func (m *defaultAmPromptTemplateModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aiModelDbAmPromptTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateIdPrefix, id)
	aiModelDbAmPromptTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateTemplateIdPrefix, data.TemplateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiModelDbAmPromptTemplateIdKey, aiModelDbAmPromptTemplateTemplateIdKey)
	return err
}

func (m *defaultAmPromptTemplateModel) FindOne(ctx context.Context, id int64) (*AmPromptTemplate, error) {
	aiModelDbAmPromptTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateIdPrefix, id)
	var resp AmPromptTemplate
	err := m.QueryRowCtx(ctx, &resp, aiModelDbAmPromptTemplateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amPromptTemplateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmPromptTemplateModel) FindOneByTemplateId(ctx context.Context, templateId string) (*AmPromptTemplate, error) {
	aiModelDbAmPromptTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateTemplateIdPrefix, templateId)
	var resp AmPromptTemplate
	err := m.QueryRowIndexCtx(ctx, &resp, aiModelDbAmPromptTemplateTemplateIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? limit 1", amPromptTemplateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, templateId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmPromptTemplateModel) Insert(ctx context.Context, data *AmPromptTemplate) (sql.Result, error) {
	aiModelDbAmPromptTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateIdPrefix, data.Id)
	aiModelDbAmPromptTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateTemplateIdPrefix, data.TemplateId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amPromptTemplateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TemplateId, data.TemplateName, data.Category, data.Content, data.Variables, data.Version, data.IsActive, data.UsageCount, data.Description, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, aiModelDbAmPromptTemplateIdKey, aiModelDbAmPromptTemplateTemplateIdKey)
	return ret, err
}

func (m *defaultAmPromptTemplateModel) Update(ctx context.Context, newData *AmPromptTemplate) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aiModelDbAmPromptTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateIdPrefix, data.Id)
	aiModelDbAmPromptTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateTemplateIdPrefix, data.TemplateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amPromptTemplateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TemplateId, newData.TemplateName, newData.Category, newData.Content, newData.Variables, newData.Version, newData.IsActive, newData.UsageCount, newData.Description, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, aiModelDbAmPromptTemplateIdKey, aiModelDbAmPromptTemplateTemplateIdKey)
	return err
}

func (m *defaultAmPromptTemplateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiModelDbAmPromptTemplateIdPrefix, primary)
}

func (m *defaultAmPromptTemplateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amPromptTemplateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmPromptTemplateModel) tableName() string {
	return m.table
}
