// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: masterdata.proto

package masterdata

import (
	"context"

	"github.com/guxiao/community-and-home/services/masterdata/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateDivisionReq                 = pb.CreateDivisionReq
	CreateDivisionResp                = pb.CreateDivisionResp
	DeleteDivisionReq                 = pb.DeleteDivisionReq
	DeleteDivisionResp                = pb.DeleteDivisionResp
	Division                          = pb.Division
	DivisionTree                      = pb.DivisionTree
	GetDivisionPathReq                = pb.GetDivisionPathReq
	GetDivisionPathResp               = pb.GetDivisionPathResp
	GetDivisionReq                    = pb.GetDivisionReq
	GetDivisionResp                   = pb.GetDivisionResp
	GetDivisionTreeReq                = pb.GetDivisionTreeReq
	GetDivisionTreeResp               = pb.GetDivisionTreeResp
	GetDivisionsByIdsReq              = pb.GetDivisionsByIdsReq
	GetDivisionsByIdsResp             = pb.GetDivisionsByIdsResp
	GetResidentialAreaReq             = pb.GetResidentialAreaReq
	GetResidentialAreaResp            = pb.GetResidentialAreaResp
	GetResidentialAreasByDivisionReq  = pb.GetResidentialAreasByDivisionReq
	GetResidentialAreasByDivisionResp = pb.GetResidentialAreasByDivisionResp
	GetResidentialAreasByIdsReq       = pb.GetResidentialAreasByIdsReq
	GetResidentialAreasByIdsResp      = pb.GetResidentialAreasByIdsResp
	ResidentialArea                   = pb.ResidentialArea
	UpdateDivisionReq                 = pb.UpdateDivisionReq
	UpdateDivisionResp                = pb.UpdateDivisionResp
	ValidateScopeReq                  = pb.ValidateScopeReq
	ValidateScopeResp                 = pb.ValidateScopeResp

	Masterdata interface {
		// Division RPC methods
		GetDivision(ctx context.Context, in *GetDivisionReq, opts ...grpc.CallOption) (*GetDivisionResp, error)
		GetDivisionsByIds(ctx context.Context, in *GetDivisionsByIdsReq, opts ...grpc.CallOption) (*GetDivisionsByIdsResp, error)
		GetDivisionTree(ctx context.Context, in *GetDivisionTreeReq, opts ...grpc.CallOption) (*GetDivisionTreeResp, error)
		GetDivisionPath(ctx context.Context, in *GetDivisionPathReq, opts ...grpc.CallOption) (*GetDivisionPathResp, error)
		ValidateScope(ctx context.Context, in *ValidateScopeReq, opts ...grpc.CallOption) (*ValidateScopeResp, error)
		CreateDivision(ctx context.Context, in *CreateDivisionReq, opts ...grpc.CallOption) (*CreateDivisionResp, error)
		UpdateDivision(ctx context.Context, in *UpdateDivisionReq, opts ...grpc.CallOption) (*UpdateDivisionResp, error)
		DeleteDivision(ctx context.Context, in *DeleteDivisionReq, opts ...grpc.CallOption) (*DeleteDivisionResp, error)
		// Residential Area RPC methods
		GetResidentialArea(ctx context.Context, in *GetResidentialAreaReq, opts ...grpc.CallOption) (*GetResidentialAreaResp, error)
		GetResidentialAreasByIds(ctx context.Context, in *GetResidentialAreasByIdsReq, opts ...grpc.CallOption) (*GetResidentialAreasByIdsResp, error)
		GetResidentialAreasByDivision(ctx context.Context, in *GetResidentialAreasByDivisionReq, opts ...grpc.CallOption) (*GetResidentialAreasByDivisionResp, error)
	}

	defaultMasterdata struct {
		cli zrpc.Client
	}
)

func NewMasterdata(cli zrpc.Client) Masterdata {
	return &defaultMasterdata{
		cli: cli,
	}
}

// Division RPC methods
func (m *defaultMasterdata) GetDivision(ctx context.Context, in *GetDivisionReq, opts ...grpc.CallOption) (*GetDivisionResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetDivision(ctx, in, opts...)
}

func (m *defaultMasterdata) GetDivisionsByIds(ctx context.Context, in *GetDivisionsByIdsReq, opts ...grpc.CallOption) (*GetDivisionsByIdsResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetDivisionsByIds(ctx, in, opts...)
}

func (m *defaultMasterdata) GetDivisionTree(ctx context.Context, in *GetDivisionTreeReq, opts ...grpc.CallOption) (*GetDivisionTreeResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetDivisionTree(ctx, in, opts...)
}

func (m *defaultMasterdata) GetDivisionPath(ctx context.Context, in *GetDivisionPathReq, opts ...grpc.CallOption) (*GetDivisionPathResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetDivisionPath(ctx, in, opts...)
}

func (m *defaultMasterdata) ValidateScope(ctx context.Context, in *ValidateScopeReq, opts ...grpc.CallOption) (*ValidateScopeResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.ValidateScope(ctx, in, opts...)
}

func (m *defaultMasterdata) CreateDivision(ctx context.Context, in *CreateDivisionReq, opts ...grpc.CallOption) (*CreateDivisionResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.CreateDivision(ctx, in, opts...)
}

func (m *defaultMasterdata) UpdateDivision(ctx context.Context, in *UpdateDivisionReq, opts ...grpc.CallOption) (*UpdateDivisionResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.UpdateDivision(ctx, in, opts...)
}

func (m *defaultMasterdata) DeleteDivision(ctx context.Context, in *DeleteDivisionReq, opts ...grpc.CallOption) (*DeleteDivisionResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.DeleteDivision(ctx, in, opts...)
}

// Residential Area RPC methods
func (m *defaultMasterdata) GetResidentialArea(ctx context.Context, in *GetResidentialAreaReq, opts ...grpc.CallOption) (*GetResidentialAreaResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetResidentialArea(ctx, in, opts...)
}

func (m *defaultMasterdata) GetResidentialAreasByIds(ctx context.Context, in *GetResidentialAreasByIdsReq, opts ...grpc.CallOption) (*GetResidentialAreasByIdsResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetResidentialAreasByIds(ctx, in, opts...)
}

func (m *defaultMasterdata) GetResidentialAreasByDivision(ctx context.Context, in *GetResidentialAreasByDivisionReq, opts ...grpc.CallOption) (*GetResidentialAreasByDivisionResp, error) {
	client := pb.NewMasterdataClient(m.cli.Conn())
	return client.GetResidentialAreasByDivision(ctx, in, opts...)
}
