// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authRoleFieldNames          = builder.RawFieldNames(&AuthRole{})
	authRoleRows                = strings.Join(authRoleFieldNames, ",")
	authRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(authRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(authRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthRoleIdPrefix   = "cache:authRole:id:"
	cacheAuthRoleCodePrefix = "cache:authRole:code:"
)

type (
	authRoleModel interface {
		Insert(ctx context.Context, data *AuthRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthRole, error)
		FindOneByCode(ctx context.Context, code string) (*AuthRole, error)
		Update(ctx context.Context, data *AuthRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthRoleModel struct {
		sqlc.CachedConn
		table string
	}

	AuthRole struct {
		Id          int64          `db:"id"`
		Name        string         `db:"name"`
		Code        string         `db:"code"`
		Description sql.NullString `db:"description"`
		IsSystem    int64          `db:"is_system"`
		SortOrder   int64          `db:"sort_order"`
		Status      int64          `db:"status"`
		CreatedBy   int64          `db:"created_by"`
		CreatedTime time.Time      `db:"created_time"`
		UpdatedTime time.Time      `db:"updated_time"`
		DeleteTime  sql.NullTime   `db:"delete_time"`
	}
)

func newAuthRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthRoleModel {
	return &defaultAuthRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_role`",
	}
}

func (m *defaultAuthRoleModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authRoleCodeKey := fmt.Sprintf("%s%v", cacheAuthRoleCodePrefix, data.Code)
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authRoleCodeKey, authRoleIdKey)
	return err
}

func (m *defaultAuthRoleModel) FindOne(ctx context.Context, id int64) (*AuthRole, error) {
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, id)
	var resp AuthRole
	err := m.QueryRowCtx(ctx, &resp, authRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthRoleModel) FindOneByCode(ctx context.Context, code string) (*AuthRole, error) {
	authRoleCodeKey := fmt.Sprintf("%s%v", cacheAuthRoleCodePrefix, code)
	var resp AuthRole
	err := m.QueryRowIndexCtx(ctx, &resp, authRoleCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", authRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthRoleModel) Insert(ctx context.Context, data *AuthRole) (sql.Result, error) {
	authRoleCodeKey := fmt.Sprintf("%s%v", cacheAuthRoleCodePrefix, data.Code)
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.Description, data.IsSystem, data.SortOrder, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, authRoleCodeKey, authRoleIdKey)
	return ret, err
}

func (m *defaultAuthRoleModel) Update(ctx context.Context, newData *AuthRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authRoleCodeKey := fmt.Sprintf("%s%v", cacheAuthRoleCodePrefix, data.Code)
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Description, newData.IsSystem, newData.SortOrder, newData.Status, newData.CreatedBy, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, authRoleCodeKey, authRoleIdKey)
	return err
}

func (m *defaultAuthRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, primary)
}

func (m *defaultAuthRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthRoleModel) tableName() string {
	return m.table
}
