// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authPropertyUnitFieldNames          = builder.RawFieldNames(&AuthPropertyUnit{})
	authPropertyUnitRows                = strings.Join(authPropertyUnitFieldNames, ",")
	authPropertyUnitRowsExpectAutoSet   = strings.Join(stringx.Remove(authPropertyUnitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authPropertyUnitRowsWithPlaceHolder = strings.Join(stringx.Remove(authPropertyUnitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthPropertyUnitIdPrefix                      = "cache:authPropertyUnit:id:"
	cacheAuthPropertyUnitCommunityIdBuildingUnitPrefix = "cache:authPropertyUnit:communityId:building:unit:"
)

type (
	authPropertyUnitModel interface {
		Insert(ctx context.Context, data *AuthPropertyUnit) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthPropertyUnit, error)
		FindOneByCommunityIdBuildingUnit(ctx context.Context, communityId int64, building string, unit string) (*AuthPropertyUnit, error)
		Update(ctx context.Context, data *AuthPropertyUnit) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthPropertyUnitModel struct {
		sqlc.CachedConn
		table string
	}

	AuthPropertyUnit struct {
		Id           int64           `db:"id"`
		CommunityId  int64           `db:"community_id"`
		Building     string          `db:"building"`
		Unit         string          `db:"unit"`
		Floor        sql.NullString  `db:"floor"`
		Area         sql.NullFloat64 `db:"area"`
		PropertyType int64           `db:"property_type"`
		Status       int64           `db:"status"`
		CreatedTime  time.Time       `db:"created_time"`
		UpdatedTime  time.Time       `db:"updated_time"`
		DeleteTime   sql.NullTime    `db:"delete_time"`
	}
)

func newAuthPropertyUnitModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthPropertyUnitModel {
	return &defaultAuthPropertyUnitModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_property_unit`",
	}
}

func (m *defaultAuthPropertyUnitModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authPropertyUnitCommunityIdBuildingUnitKey := fmt.Sprintf("%s%v:%v:%v", cacheAuthPropertyUnitCommunityIdBuildingUnitPrefix, data.CommunityId, data.Building, data.Unit)
	authPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyUnitIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authPropertyUnitCommunityIdBuildingUnitKey, authPropertyUnitIdKey)
	return err
}

func (m *defaultAuthPropertyUnitModel) FindOne(ctx context.Context, id int64) (*AuthPropertyUnit, error) {
	authPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyUnitIdPrefix, id)
	var resp AuthPropertyUnit
	err := m.QueryRowCtx(ctx, &resp, authPropertyUnitIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authPropertyUnitRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthPropertyUnitModel) FindOneByCommunityIdBuildingUnit(ctx context.Context, communityId int64, building string, unit string) (*AuthPropertyUnit, error) {
	authPropertyUnitCommunityIdBuildingUnitKey := fmt.Sprintf("%s%v:%v:%v", cacheAuthPropertyUnitCommunityIdBuildingUnitPrefix, communityId, building, unit)
	var resp AuthPropertyUnit
	err := m.QueryRowIndexCtx(ctx, &resp, authPropertyUnitCommunityIdBuildingUnitKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `community_id` = ? and `building` = ? and `unit` = ? limit 1", authPropertyUnitRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, communityId, building, unit); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthPropertyUnitModel) Insert(ctx context.Context, data *AuthPropertyUnit) (sql.Result, error) {
	authPropertyUnitCommunityIdBuildingUnitKey := fmt.Sprintf("%s%v:%v:%v", cacheAuthPropertyUnitCommunityIdBuildingUnitPrefix, data.CommunityId, data.Building, data.Unit)
	authPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyUnitIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authPropertyUnitRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CommunityId, data.Building, data.Unit, data.Floor, data.Area, data.PropertyType, data.Status, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, authPropertyUnitCommunityIdBuildingUnitKey, authPropertyUnitIdKey)
	return ret, err
}

func (m *defaultAuthPropertyUnitModel) Update(ctx context.Context, newData *AuthPropertyUnit) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authPropertyUnitCommunityIdBuildingUnitKey := fmt.Sprintf("%s%v:%v:%v", cacheAuthPropertyUnitCommunityIdBuildingUnitPrefix, data.CommunityId, data.Building, data.Unit)
	authPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyUnitIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authPropertyUnitRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CommunityId, newData.Building, newData.Unit, newData.Floor, newData.Area, newData.PropertyType, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, authPropertyUnitCommunityIdBuildingUnitKey, authPropertyUnitIdKey)
	return err
}

func (m *defaultAuthPropertyUnitModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthPropertyUnitIdPrefix, primary)
}

func (m *defaultAuthPropertyUnitModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authPropertyUnitRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthPropertyUnitModel) tableName() string {
	return m.table
}
