// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authHomeownerVerificationFieldNames          = builder.RawFieldNames(&AuthHomeownerVerification{})
	authHomeownerVerificationRows                = strings.Join(authHomeownerVerificationFieldNames, ",")
	authHomeownerVerificationRowsExpectAutoSet   = strings.Join(stringx.Remove(authHomeownerVerificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authHomeownerVerificationRowsWithPlaceHolder = strings.Join(stringx.Remove(authHomeownerVerificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthHomeownerVerificationIdPrefix = "cache:authHomeownerVerification:id:"
)

type (
	authHomeownerVerificationModel interface {
		Insert(ctx context.Context, data *AuthHomeownerVerification) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthHomeownerVerification, error)
		Update(ctx context.Context, data *AuthHomeownerVerification) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthHomeownerVerificationModel struct {
		sqlc.CachedConn
		table string
	}

	AuthHomeownerVerification struct {
		Id                 int64          `db:"id"`
		UserId             int64          `db:"user_id"`
		PropertyUnitId     int64          `db:"property_unit_id"`
		DocumentUrls       string         `db:"document_urls"`
		RealName           string         `db:"real_name"`
		IdCardNumber       string         `db:"id_card_number"`
		VerificationStatus int64          `db:"verification_status"`
		ReviewerId         sql.NullInt64  `db:"reviewer_id"`
		ReviewTime         sql.NullTime   `db:"review_time"`
		ReviewNotes        sql.NullString `db:"review_notes"`
		SubmitTime         time.Time      `db:"submit_time"`
		CreatedTime        time.Time      `db:"created_time"`
		UpdatedTime        time.Time      `db:"updated_time"`
	}
)

func newAuthHomeownerVerificationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthHomeownerVerificationModel {
	return &defaultAuthHomeownerVerificationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_homeowner_verification`",
	}
}

func (m *defaultAuthHomeownerVerificationModel) Delete(ctx context.Context, id int64) error {
	authHomeownerVerificationIdKey := fmt.Sprintf("%s%v", cacheAuthHomeownerVerificationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authHomeownerVerificationIdKey)
	return err
}

func (m *defaultAuthHomeownerVerificationModel) FindOne(ctx context.Context, id int64) (*AuthHomeownerVerification, error) {
	authHomeownerVerificationIdKey := fmt.Sprintf("%s%v", cacheAuthHomeownerVerificationIdPrefix, id)
	var resp AuthHomeownerVerification
	err := m.QueryRowCtx(ctx, &resp, authHomeownerVerificationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authHomeownerVerificationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthHomeownerVerificationModel) Insert(ctx context.Context, data *AuthHomeownerVerification) (sql.Result, error) {
	authHomeownerVerificationIdKey := fmt.Sprintf("%s%v", cacheAuthHomeownerVerificationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authHomeownerVerificationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.PropertyUnitId, data.DocumentUrls, data.RealName, data.IdCardNumber, data.VerificationStatus, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.SubmitTime, data.CreatedTime, data.UpdatedTime)
	}, authHomeownerVerificationIdKey)
	return ret, err
}

func (m *defaultAuthHomeownerVerificationModel) Update(ctx context.Context, data *AuthHomeownerVerification) error {
	authHomeownerVerificationIdKey := fmt.Sprintf("%s%v", cacheAuthHomeownerVerificationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authHomeownerVerificationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.PropertyUnitId, data.DocumentUrls, data.RealName, data.IdCardNumber, data.VerificationStatus, data.ReviewerId, data.ReviewTime, data.ReviewNotes, data.SubmitTime, data.CreatedTime, data.UpdatedTime, data.Id)
	}, authHomeownerVerificationIdKey)
	return err
}

func (m *defaultAuthHomeownerVerificationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthHomeownerVerificationIdPrefix, primary)
}

func (m *defaultAuthHomeownerVerificationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authHomeownerVerificationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthHomeownerVerificationModel) tableName() string {
	return m.table
}
