// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authFamilyMemberFieldNames          = builder.RawFieldNames(&AuthFamilyMember{})
	authFamilyMemberRows                = strings.Join(authFamilyMemberFieldNames, ",")
	authFamilyMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(authFamilyMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authFamilyMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(authFamilyMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthFamilyMemberIdPrefix = "cache:authFamilyMember:id:"
)

type (
	authFamilyMemberModel interface {
		Insert(ctx context.Context, data *AuthFamilyMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthFamilyMember, error)
		Update(ctx context.Context, data *AuthFamilyMember) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthFamilyMemberModel struct {
		sqlc.CachedConn
		table string
	}

	AuthFamilyMember struct {
		Id           int64          `db:"id"`
		FamilyId     int64          `db:"family_id"`
		UserId       sql.NullInt64  `db:"user_id"`
		Name         string         `db:"name"`
		Relationship string         `db:"relationship"`
		Phone        sql.NullString `db:"phone"`
		IdCardNumber sql.NullString `db:"id_card_number"`
		BirthDate    sql.NullTime   `db:"birth_date"`
		Gender       sql.NullInt64  `db:"gender"`
		CreatedTime  time.Time      `db:"created_time"`
		UpdatedTime  time.Time      `db:"updated_time"`
		DeleteTime   sql.NullTime   `db:"delete_time"`
	}
)

func newAuthFamilyMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthFamilyMemberModel {
	return &defaultAuthFamilyMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_family_member`",
	}
}

func (m *defaultAuthFamilyMemberModel) Delete(ctx context.Context, id int64) error {
	authFamilyMemberIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyMemberIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authFamilyMemberIdKey)
	return err
}

func (m *defaultAuthFamilyMemberModel) FindOne(ctx context.Context, id int64) (*AuthFamilyMember, error) {
	authFamilyMemberIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyMemberIdPrefix, id)
	var resp AuthFamilyMember
	err := m.QueryRowCtx(ctx, &resp, authFamilyMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authFamilyMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthFamilyMemberModel) Insert(ctx context.Context, data *AuthFamilyMember) (sql.Result, error) {
	authFamilyMemberIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authFamilyMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FamilyId, data.UserId, data.Name, data.Relationship, data.Phone, data.IdCardNumber, data.BirthDate, data.Gender, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, authFamilyMemberIdKey)
	return ret, err
}

func (m *defaultAuthFamilyMemberModel) Update(ctx context.Context, data *AuthFamilyMember) error {
	authFamilyMemberIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyMemberIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authFamilyMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FamilyId, data.UserId, data.Name, data.Relationship, data.Phone, data.IdCardNumber, data.BirthDate, data.Gender, data.CreatedTime, data.UpdatedTime, data.DeleteTime, data.Id)
	}, authFamilyMemberIdKey)
	return err
}

func (m *defaultAuthFamilyMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthFamilyMemberIdPrefix, primary)
}

func (m *defaultAuthFamilyMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authFamilyMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthFamilyMemberModel) tableName() string {
	return m.table
}
