// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authUploadedFileFieldNames          = builder.RawFieldNames(&AuthUploadedFile{})
	authUploadedFileRows                = strings.Join(authUploadedFileFieldNames, ",")
	authUploadedFileRowsExpectAutoSet   = strings.Join(stringx.Remove(authUploadedFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authUploadedFileRowsWithPlaceHolder = strings.Join(stringx.Remove(authUploadedFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthUploadedFileIdPrefix = "cache:authUploadedFile:id:"
)

type (
	authUploadedFileModel interface {
		Insert(ctx context.Context, data *AuthUploadedFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthUploadedFile, error)
		Update(ctx context.Context, data *AuthUploadedFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthUploadedFileModel struct {
		sqlc.CachedConn
		table string
	}

	AuthUploadedFile struct {
		Id          int64     `db:"id"`
		UserId      int64     `db:"user_id"`
		EntityType  string    `db:"entity_type"`
		EntityId    int64     `db:"entity_id"`
		FileName    string    `db:"file_name"`
		FilePath    string    `db:"file_path"`
		FileSize    int64     `db:"file_size"`
		FileType    string    `db:"file_type"`
		BucketName  string    `db:"bucket_name"`
		UploadTime  time.Time `db:"upload_time"`
		CreatedTime time.Time `db:"created_time"`
	}
)

func newAuthUploadedFileModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthUploadedFileModel {
	return &defaultAuthUploadedFileModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_uploaded_file`",
	}
}

func (m *defaultAuthUploadedFileModel) Delete(ctx context.Context, id int64) error {
	authUploadedFileIdKey := fmt.Sprintf("%s%v", cacheAuthUploadedFileIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authUploadedFileIdKey)
	return err
}

func (m *defaultAuthUploadedFileModel) FindOne(ctx context.Context, id int64) (*AuthUploadedFile, error) {
	authUploadedFileIdKey := fmt.Sprintf("%s%v", cacheAuthUploadedFileIdPrefix, id)
	var resp AuthUploadedFile
	err := m.QueryRowCtx(ctx, &resp, authUploadedFileIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUploadedFileRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUploadedFileModel) Insert(ctx context.Context, data *AuthUploadedFile) (sql.Result, error) {
	authUploadedFileIdKey := fmt.Sprintf("%s%v", cacheAuthUploadedFileIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authUploadedFileRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.EntityType, data.EntityId, data.FileName, data.FilePath, data.FileSize, data.FileType, data.BucketName, data.UploadTime, data.CreatedTime)
	}, authUploadedFileIdKey)
	return ret, err
}

func (m *defaultAuthUploadedFileModel) Update(ctx context.Context, data *AuthUploadedFile) error {
	authUploadedFileIdKey := fmt.Sprintf("%s%v", cacheAuthUploadedFileIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authUploadedFileRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.EntityType, data.EntityId, data.FileName, data.FilePath, data.FileSize, data.FileType, data.BucketName, data.UploadTime, data.CreatedTime, data.Id)
	}, authUploadedFileIdKey)
	return err
}

func (m *defaultAuthUploadedFileModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthUploadedFileIdPrefix, primary)
}

func (m *defaultAuthUploadedFileModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUploadedFileRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthUploadedFileModel) tableName() string {
	return m.table
}
