// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authUserRoleFieldNames          = builder.RawFieldNames(&AuthUserRole{})
	authUserRoleRows                = strings.Join(authUserRoleFieldNames, ",")
	authUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(authUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(authUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthUserRoleIdPrefix           = "cache:authUserRole:id:"
	cacheAuthUserRoleUserIdRoleIdPrefix = "cache:authUserRole:userId:roleId:"
)

type (
	authUserRoleModel interface {
		Insert(ctx context.Context, data *AuthUserRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthUserRole, error)
		FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*AuthUserRole, error)
		Update(ctx context.Context, data *AuthUserRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	AuthUserRole struct {
		Id          int64     `db:"id"`
		UserId      int64     `db:"user_id"`
		RoleId      int64     `db:"role_id"`
		CreatedTime time.Time `db:"created_time"`
	}
)

func newAuthUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthUserRoleModel {
	return &defaultAuthUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_user_role`",
	}
}

func (m *defaultAuthUserRoleModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authUserRoleIdKey := fmt.Sprintf("%s%v", cacheAuthUserRoleIdPrefix, id)
	authUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheAuthUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authUserRoleIdKey, authUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultAuthUserRoleModel) FindOne(ctx context.Context, id int64) (*AuthUserRole, error) {
	authUserRoleIdKey := fmt.Sprintf("%s%v", cacheAuthUserRoleIdPrefix, id)
	var resp AuthUserRole
	err := m.QueryRowCtx(ctx, &resp, authUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUserRoleModel) FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*AuthUserRole, error) {
	authUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheAuthUserRoleUserIdRoleIdPrefix, userId, roleId)
	var resp AuthUserRole
	err := m.QueryRowIndexCtx(ctx, &resp, authUserRoleUserIdRoleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? limit 1", authUserRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, roleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUserRoleModel) Insert(ctx context.Context, data *AuthUserRole) (sql.Result, error) {
	authUserRoleIdKey := fmt.Sprintf("%s%v", cacheAuthUserRoleIdPrefix, data.Id)
	authUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheAuthUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, authUserRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.CreatedTime)
	}, authUserRoleIdKey, authUserRoleUserIdRoleIdKey)
	return ret, err
}

func (m *defaultAuthUserRoleModel) Update(ctx context.Context, newData *AuthUserRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authUserRoleIdKey := fmt.Sprintf("%s%v", cacheAuthUserRoleIdPrefix, data.Id)
	authUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheAuthUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authUserRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.RoleId, newData.CreatedTime, newData.Id)
	}, authUserRoleIdKey, authUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultAuthUserRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthUserRoleIdPrefix, primary)
}

func (m *defaultAuthUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUserRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthUserRoleModel) tableName() string {
	return m.table
}
