// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authUserFieldNames          = builder.RawFieldNames(&AuthUser{})
	authUserRows                = strings.Join(authUserFieldNames, ",")
	authUserRowsExpectAutoSet   = strings.Join(stringx.Remove(authUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authUserRowsWithPlaceHolder = strings.Join(stringx.Remove(authUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthUserIdPrefix    = "cache:authUser:id:"
	cacheAuthUserPhonePrefix = "cache:authUser:phone:"
)

type (
	authUserModel interface {
		Insert(ctx context.Context, data *AuthUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthUser, error)
		FindOneByPhone(ctx context.Context, phone string) (*AuthUser, error)
		Update(ctx context.Context, data *AuthUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthUserModel struct {
		sqlc.CachedConn
		table string
	}

	AuthUser struct {
		Id                 int64          `db:"id"`
		Phone              string         `db:"phone"`
		PasswordHash       string         `db:"password_hash"`
		Nickname           sql.NullString `db:"nickname"`
		AvatarUrl          sql.NullString `db:"avatar_url"`
		UserType           int64          `db:"user_type"`
		Status             int64          `db:"status"`
		VerificationStatus int64          `db:"verification_status"`
		ScopeId            sql.NullInt64  `db:"scope_id"`
		LastLoginTime      sql.NullTime   `db:"last_login_time"`
		LastLoginIp        sql.NullString `db:"last_login_ip"`
		CreatedTime        time.Time      `db:"created_time"`
		UpdatedTime        time.Time      `db:"updated_time"`
		DeleteTime         sql.NullTime   `db:"delete_time"`
	}
)

func newAuthUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthUserModel {
	return &defaultAuthUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_user`",
	}
}

func (m *defaultAuthUserModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authUserIdKey := fmt.Sprintf("%s%v", cacheAuthUserIdPrefix, id)
	authUserPhoneKey := fmt.Sprintf("%s%v", cacheAuthUserPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authUserIdKey, authUserPhoneKey)
	return err
}

func (m *defaultAuthUserModel) FindOne(ctx context.Context, id int64) (*AuthUser, error) {
	authUserIdKey := fmt.Sprintf("%s%v", cacheAuthUserIdPrefix, id)
	var resp AuthUser
	err := m.QueryRowCtx(ctx, &resp, authUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUserModel) FindOneByPhone(ctx context.Context, phone string) (*AuthUser, error) {
	authUserPhoneKey := fmt.Sprintf("%s%v", cacheAuthUserPhonePrefix, phone)
	var resp AuthUser
	err := m.QueryRowIndexCtx(ctx, &resp, authUserPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", authUserRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUserModel) Insert(ctx context.Context, data *AuthUser) (sql.Result, error) {
	authUserIdKey := fmt.Sprintf("%s%v", cacheAuthUserIdPrefix, data.Id)
	authUserPhoneKey := fmt.Sprintf("%s%v", cacheAuthUserPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.PasswordHash, data.Nickname, data.AvatarUrl, data.UserType, data.Status, data.VerificationStatus, data.ScopeId, data.LastLoginTime, data.LastLoginIp, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, authUserIdKey, authUserPhoneKey)
	return ret, err
}

func (m *defaultAuthUserModel) Update(ctx context.Context, newData *AuthUser) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authUserIdKey := fmt.Sprintf("%s%v", cacheAuthUserIdPrefix, data.Id)
	authUserPhoneKey := fmt.Sprintf("%s%v", cacheAuthUserPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Phone, newData.PasswordHash, newData.Nickname, newData.AvatarUrl, newData.UserType, newData.Status, newData.VerificationStatus, newData.ScopeId, newData.LastLoginTime, newData.LastLoginIp, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, authUserIdKey, authUserPhoneKey)
	return err
}

func (m *defaultAuthUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthUserIdPrefix, primary)
}

func (m *defaultAuthUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthUserModel) tableName() string {
	return m.table
}
