// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authFamilyFieldNames          = builder.RawFieldNames(&AuthFamily{})
	authFamilyRows                = strings.Join(authFamilyFieldNames, ",")
	authFamilyRowsExpectAutoSet   = strings.Join(stringx.Remove(authFamilyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authFamilyRowsWithPlaceHolder = strings.Join(stringx.Remove(authFamilyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthFamilyIdPrefix             = "cache:authFamily:id:"
	cacheAuthFamilyPropertyUnitIdPrefix = "cache:authFamily:propertyUnitId:"
)

type (
	authFamilyModel interface {
		Insert(ctx context.Context, data *AuthFamily) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthFamily, error)
		FindOneByPropertyUnitId(ctx context.Context, propertyUnitId int64) (*AuthFamily, error)
		Update(ctx context.Context, data *AuthFamily) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthFamilyModel struct {
		sqlc.CachedConn
		table string
	}

	AuthFamily struct {
		Id             int64          `db:"id"`
		PropertyUnitId int64          `db:"property_unit_id"`
		FamilyHeadId   int64          `db:"family_head_id"`
		FamilyName     sql.NullString `db:"family_name"`
		Status         int64          `db:"status"`
		CreatedTime    time.Time      `db:"created_time"`
		UpdatedTime    time.Time      `db:"updated_time"`
		DeleteTime     sql.NullTime   `db:"delete_time"`
	}
)

func newAuthFamilyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthFamilyModel {
	return &defaultAuthFamilyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_family`",
	}
}

func (m *defaultAuthFamilyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authFamilyIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyIdPrefix, id)
	authFamilyPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyPropertyUnitIdPrefix, data.PropertyUnitId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authFamilyIdKey, authFamilyPropertyUnitIdKey)
	return err
}

func (m *defaultAuthFamilyModel) FindOne(ctx context.Context, id int64) (*AuthFamily, error) {
	authFamilyIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyIdPrefix, id)
	var resp AuthFamily
	err := m.QueryRowCtx(ctx, &resp, authFamilyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authFamilyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthFamilyModel) FindOneByPropertyUnitId(ctx context.Context, propertyUnitId int64) (*AuthFamily, error) {
	authFamilyPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyPropertyUnitIdPrefix, propertyUnitId)
	var resp AuthFamily
	err := m.QueryRowIndexCtx(ctx, &resp, authFamilyPropertyUnitIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `property_unit_id` = ? limit 1", authFamilyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, propertyUnitId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthFamilyModel) Insert(ctx context.Context, data *AuthFamily) (sql.Result, error) {
	authFamilyIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyIdPrefix, data.Id)
	authFamilyPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyPropertyUnitIdPrefix, data.PropertyUnitId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, authFamilyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PropertyUnitId, data.FamilyHeadId, data.FamilyName, data.Status, data.CreatedTime, data.UpdatedTime, data.DeleteTime)
	}, authFamilyIdKey, authFamilyPropertyUnitIdKey)
	return ret, err
}

func (m *defaultAuthFamilyModel) Update(ctx context.Context, newData *AuthFamily) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authFamilyIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyIdPrefix, data.Id)
	authFamilyPropertyUnitIdKey := fmt.Sprintf("%s%v", cacheAuthFamilyPropertyUnitIdPrefix, data.PropertyUnitId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authFamilyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PropertyUnitId, newData.FamilyHeadId, newData.FamilyName, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.DeleteTime, newData.Id)
	}, authFamilyIdKey, authFamilyPropertyUnitIdKey)
	return err
}

func (m *defaultAuthFamilyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthFamilyIdPrefix, primary)
}

func (m *defaultAuthFamilyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authFamilyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthFamilyModel) tableName() string {
	return m.table
}
