// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authPropertyBindingFieldNames          = builder.RawFieldNames(&AuthPropertyBinding{})
	authPropertyBindingRows                = strings.Join(authPropertyBindingFieldNames, ",")
	authPropertyBindingRowsExpectAutoSet   = strings.Join(stringx.Remove(authPropertyBindingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authPropertyBindingRowsWithPlaceHolder = strings.Join(stringx.Remove(authPropertyBindingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthPropertyBindingIdPrefix                   = "cache:authPropertyBinding:id:"
	cacheAuthPropertyBindingUserIdPropertyUnitIdPrefix = "cache:authPropertyBinding:userId:propertyUnitId:"
)

type (
	authPropertyBindingModel interface {
		Insert(ctx context.Context, data *AuthPropertyBinding) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthPropertyBinding, error)
		FindOneByUserIdPropertyUnitId(ctx context.Context, userId int64, propertyUnitId int64) (*AuthPropertyBinding, error)
		Update(ctx context.Context, data *AuthPropertyBinding) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthPropertyBindingModel struct {
		sqlc.CachedConn
		table string
	}

	AuthPropertyBinding struct {
		Id             int64         `db:"id"`
		UserId         int64         `db:"user_id"`
		PropertyUnitId int64         `db:"property_unit_id"`
		IsPrimary      int64         `db:"is_primary"`
		BindStatus     int64         `db:"bind_status"`
		BindTime       time.Time     `db:"bind_time"`
		RevokeTime     sql.NullTime  `db:"revoke_time"`
		RevokedBy      sql.NullInt64 `db:"revoked_by"`
		CreatedTime    time.Time     `db:"created_time"`
		UpdatedTime    time.Time     `db:"updated_time"`
	}
)

func newAuthPropertyBindingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthPropertyBindingModel {
	return &defaultAuthPropertyBindingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_property_binding`",
	}
}

func (m *defaultAuthPropertyBindingModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authPropertyBindingIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyBindingIdPrefix, id)
	authPropertyBindingUserIdPropertyUnitIdKey := fmt.Sprintf("%s%v:%v", cacheAuthPropertyBindingUserIdPropertyUnitIdPrefix, data.UserId, data.PropertyUnitId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authPropertyBindingIdKey, authPropertyBindingUserIdPropertyUnitIdKey)
	return err
}

func (m *defaultAuthPropertyBindingModel) FindOne(ctx context.Context, id int64) (*AuthPropertyBinding, error) {
	authPropertyBindingIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyBindingIdPrefix, id)
	var resp AuthPropertyBinding
	err := m.QueryRowCtx(ctx, &resp, authPropertyBindingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authPropertyBindingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthPropertyBindingModel) FindOneByUserIdPropertyUnitId(ctx context.Context, userId int64, propertyUnitId int64) (*AuthPropertyBinding, error) {
	authPropertyBindingUserIdPropertyUnitIdKey := fmt.Sprintf("%s%v:%v", cacheAuthPropertyBindingUserIdPropertyUnitIdPrefix, userId, propertyUnitId)
	var resp AuthPropertyBinding
	err := m.QueryRowIndexCtx(ctx, &resp, authPropertyBindingUserIdPropertyUnitIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `property_unit_id` = ? limit 1", authPropertyBindingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, propertyUnitId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthPropertyBindingModel) Insert(ctx context.Context, data *AuthPropertyBinding) (sql.Result, error) {
	authPropertyBindingIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyBindingIdPrefix, data.Id)
	authPropertyBindingUserIdPropertyUnitIdKey := fmt.Sprintf("%s%v:%v", cacheAuthPropertyBindingUserIdPropertyUnitIdPrefix, data.UserId, data.PropertyUnitId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authPropertyBindingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.PropertyUnitId, data.IsPrimary, data.BindStatus, data.BindTime, data.RevokeTime, data.RevokedBy, data.CreatedTime, data.UpdatedTime)
	}, authPropertyBindingIdKey, authPropertyBindingUserIdPropertyUnitIdKey)
	return ret, err
}

func (m *defaultAuthPropertyBindingModel) Update(ctx context.Context, newData *AuthPropertyBinding) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authPropertyBindingIdKey := fmt.Sprintf("%s%v", cacheAuthPropertyBindingIdPrefix, data.Id)
	authPropertyBindingUserIdPropertyUnitIdKey := fmt.Sprintf("%s%v:%v", cacheAuthPropertyBindingUserIdPropertyUnitIdPrefix, data.UserId, data.PropertyUnitId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authPropertyBindingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.PropertyUnitId, newData.IsPrimary, newData.BindStatus, newData.BindTime, newData.RevokeTime, newData.RevokedBy, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, authPropertyBindingIdKey, authPropertyBindingUserIdPropertyUnitIdKey)
	return err
}

func (m *defaultAuthPropertyBindingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthPropertyBindingIdPrefix, primary)
}

func (m *defaultAuthPropertyBindingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authPropertyBindingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthPropertyBindingModel) tableName() string {
	return m.table
}
