// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResp struct {
	Status string `json:"status"`
}

type ImageCheckResp struct {
	Pass       bool          `json:"pass"`
	RiskLevel  string        `json:"risk_level"`
	Reason     string        `json:"reason"`
	NeedReview bool          `json:"need_review"`
	Details    []MatchDetail `json:"details"`
}

type MatchDetail struct {
	Layer       string  `json:"layer"`
	MatchedText string  `json:"matched_text,omitempty"`
	Category    string  `json:"category,omitempty"`
	Severity    int     `json:"severity,omitempty"`
	Confidence  float64 `json:"confidence,omitempty"`
}

type TextCheckReq struct {
	Content     string `json:"content"`
	ContentType string `json:"content_type,optional"`
	CheckMode   string `json:"check_mode,optional,default=combined"`
}

type TextCheckResp struct {
	Pass       bool          `json:"pass"`
	RiskLevel  string        `json:"risk_level"`
	Reason     string        `json:"reason"`
	NeedReview bool          `json:"need_review"`
	Details    []MatchDetail `json:"details"`
}
