// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AssignUserRolesReq struct {
	Id      int64   `path:"id"`
	RoleIds []int64 `json:"role_ids"`
}

type AssignUserRolesResp struct {
	Success bool `json:"success"`
}

type BindPropertyReq struct {
	PropertyUnitId int64 `json:"property_unit_id"`
}

type BindPropertyResp struct {
	Id int64 `json:"id"`
}

type CreateRoleReq struct {
	Name          string  `json:"name"`
	Code          string  `json:"code"`
	Description   string  `json:"description,optional"`
	PermissionIds []int64 `json:"permission_ids"`
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type CreateUserReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	UserType int32  `json:"user_type"`
	ScopeId  *int64 `json:"scope_id,optional"`
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}

type DeleteRoleReq struct {
	Id int64 `path:"id"`
}

type DeleteRoleResp struct {
	Success bool `json:"success"`
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetFileUrlReq struct {
	FileId int64 `path:"file_id"`
}

type GetFileUrlResp struct {
	FileUrl string `json:"file_url"`
}

type GetMyPropertiesReq struct {
	Page     int32  `form:"page,optional,default=1"`
	PageSize int32  `form:"page_size,optional,default=20"`
	Status   *int32 `form:"status,optional"`
}

type GetMyPropertiesResp struct {
	List  []PropertyBinding `json:"list"`
	Total int64             `json:"total"`
}

type GetMyVerificationsReq struct {
	Page     int32  `form:"page,optional,default=1"`
	PageSize int32  `form:"page_size,optional,default=20"`
	Status   *int32 `form:"status,optional"`
}

type GetMyVerificationsResp struct {
	List  []HomeownerVerification `json:"list"`
	Total int64                   `json:"total"`
}

type GetPermissionsReq struct {
	Status *int32 `form:"status,optional"`
}

type GetPermissionsResp struct {
	List []PermissionTree `json:"list"`
}

type GetRoleReq struct {
	Id int64 `path:"id"`
}

type GetRoleResp struct {
	Role RoleWithPermissions `json:"role"`
}

type GetRolesReq struct {
	Page     int32  `form:"page,optional,default=1"`
	PageSize int32  `form:"page_size,optional,default=20"`
	Status   *int32 `form:"status,optional"`
}

type GetRolesResp struct {
	List  []Role `json:"list"`
	Total int64  `json:"total"`
}

type GetUserPermissionsReq struct {
	UserId int64 `path:"id"`
}

type GetUserPermissionsResp struct {
	Permissions []string         `json:"permissions"`
	Menus       []PermissionTree `json:"menus"`
}

type GetUserReq struct {
	Id int64 `path:"id"`
}

type GetUserResp struct {
	User User `json:"user"`
}

type GetUserRolesReq struct {
	Id int64 `path:"id"`
}

type GetUserRolesResp struct {
	Roles []Role `json:"roles"`
}

type GetUsersReq struct {
	Page     int32  `form:"page,optional,default=1"`
	PageSize int32  `form:"page_size,optional,default=20"`
	UserType *int32 `form:"user_type,optional"`
	Status   *int32 `form:"status,optional"`
	ScopeId  *int64 `form:"scope_id,optional"`
}

type GetUsersResp struct {
	List  []User `json:"list"`
	Total int64  `json:"total"`
}

type GetVerificationListReq struct {
	Page     int32  `form:"page,optional,default=1"`
	PageSize int32  `form:"page_size,optional,default=20"`
	Status   *int32 `form:"status,optional"`
}

type GetVerificationListResp struct {
	List  []HomeownerVerification `json:"list"`
	Total int64                   `json:"total"`
}

type GetVerificationReq struct {
	Id int64 `path:"id"`
}

type GetVerificationResp struct {
	Verification HomeownerVerification `json:"verification"`
}

type HomeownerVerification struct {
	Id                 int64  `json:"id"`
	UserId             int64  `json:"user_id"`
	PropertyUnitId     int64  `json:"property_unit_id"`
	DocumentUrls       string `json:"document_urls"`
	RealName           string `json:"real_name"`
	IdCardNumber       string `json:"id_card_number"`
	VerificationStatus int64  `json:"verification_status"`
	ReviewerId         *int64 `json:"reviewer_id,optional"`
	ReviewTime         string `json:"review_time,optional"`
	ReviewNotes        string `json:"review_notes,optional"`
	SubmitTime         string `json:"submit_time"`
	CreatedTime        string `json:"created_time"`
	UpdatedTime        string `json:"updated_time"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
	User         User   `json:"user"`
}

type LoginSmsReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginSmsResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
	User         User   `json:"user"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type Permission struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Type        int32  `json:"type"`
	ParentId    *int64 `json:"parent_id,optional"`
	Path        string `json:"path"`
	SortOrder   int32  `json:"sort_order"`
	Status      int32  `json:"status"`
	CreatedTime string `json:"created_time"`
	UpdatedTime string `json:"updated_time"`
}

type PermissionTree struct {
	Id          int64            `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Type        int32            `json:"type"`
	ParentId    *int64           `json:"parent_id,optional"`
	Path        string           `json:"path"`
	SortOrder   int32            `json:"sort_order"`
	Status      int32            `json:"status"`
	Children    []PermissionTree `json:"children,optional"`
	CreatedTime string           `json:"created_time"`
	UpdatedTime string           `json:"updated_time"`
}

type PropertyBinding struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"user_id"`
	PropertyUnitId int64  `json:"property_unit_id"`
	IsPrimary      bool   `json:"is_primary"`
	BindStatus     int64  `json:"bind_status"`
	BindTime       string `json:"bind_time"`
	RevokeTime     string `json:"revoke_time,optional"`
	RevokedBy      int64  `json:"revoked_by,optional"`
	CreatedTime    string `json:"created_time"`
	UpdatedTime    string `json:"updated_time"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Nickname string `json:"nickname,optional"`
	Password string `json:"password,optional"`
}

type RegisterResp struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RemoveUserRoleReq struct {
	Id     int64 `path:"id"`
	RoleId int64 `path:"roleId"`
}

type RemoveUserRoleResp struct {
	Success bool `json:"success"`
}

type ReviewVerificationReq struct {
	Id          int64  `path:"id"`
	Status      int32  `json:"status"`
	ReviewNotes string `json:"review_notes,optional"`
}

type ReviewVerificationResp struct {
	Success bool `json:"success"`
}

type Role struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	IsSystem    int32  `json:"is_system"`
	Status      int32  `json:"status"`
	CreatedTime string `json:"created_time"`
	UpdatedTime string `json:"updated_time"`
}

type RoleWithPermissions struct {
	Id          int64        `json:"id"`
	Name        string       `json:"name"`
	Code        string       `json:"code"`
	Description string       `json:"description,optional"`
	IsSystem    int32        `json:"is_system"`
	Status      int32        `json:"status"`
	Permissions []Permission `json:"permissions"`
	CreatedTime string       `json:"created_time"`
	UpdatedTime string       `json:"updated_time"`
}

type SendSmsCodeReq struct {
	Phone string `json:"phone"`
}

type SendSmsCodeResp struct {
	Success bool `json:"success"`
}

type SubmitVerificationReq struct {
	PropertyUnitId int64    `json:"property_unit_id"`
	RealName       string   `json:"real_name"`
	IdCardNumber   string   `json:"id_card_number"`
	DocumentUrls   []string `json:"document_urls"`
}

type SubmitVerificationResp struct {
	Id int64 `json:"id"`
}

type UnbindPropertyReq struct {
	Id int64 `path:"id"`
}

type UnbindPropertyResp struct {
	Success bool `json:"success"`
}

type UpdateRoleReq struct {
	Id            int64   `path:"id"`
	Name          string  `json:"name,optional"`
	Description   string  `json:"description,optional"`
	Status        *int32  `json:"status,optional"`
	PermissionIds []int64 `json:"permission_ids,optional"`
}

type UpdateRoleResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Id        int64  `path:"id"`
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
	UserType  int32  `json:"user_type,optional"`
	Status    int32  `json:"status,optional"`
	ScopeId   *int64 `json:"scope_id,optional"`
	Password  string `json:"password,optional"`
}

type UpdateUserResp struct {
	Success bool `json:"success"`
}

type UploadFileReq struct {
	EntityType string `form:"entity_type"`
	EntityId   int64  `form:"entity_id"`
}

type UploadFileResp struct {
	FileId  int64  `json:"file_id"`
	FileUrl string `json:"file_url"`
}

type User struct {
	Id                 int64  `json:"id"`
	Phone              string `json:"phone"`
	Nickname           string `json:"nickname"`
	AvatarUrl          string `json:"avatar_url"`
	UserType           int32  `json:"user_type"`
	Status             int32  `json:"status"`
	VerificationStatus int32  `json:"verification_status"`
	ScopeId            *int64 `json:"scope_id"`
	CreatedTime        string `json:"created_time"`
	UpdatedTime        string `json:"updated_time"`
}
