// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/guxiao/community-and-home/services/identity/api/internal/handler/auth"
	family "github.com/guxiao/community-and-home/services/identity/api/internal/handler/family"
	file "github.com/guxiao/community-and-home/services/identity/api/internal/handler/file"
	permission "github.com/guxiao/community-and-home/services/identity/api/internal/handler/permission"
	property "github.com/guxiao/community-and-home/services/identity/api/internal/handler/property"
	role "github.com/guxiao/community-and-home/services/identity/api/internal/handler/role"
	user "github.com/guxiao/community-and-home/services/identity/api/internal/handler/user"
	verification "github.com/guxiao/community-and-home/services/identity/api/internal/handler/verification"
	"github.com/guxiao/community-and-home/services/identity/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// User login with password
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// User login with SMS code
				Method:  http.MethodPost,
				Path:    "/auth/login/sms",
				Handler: auth.LoginSmsHandler(serverCtx),
			},
			{
				// User logout
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// User register
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// Send SMS verification code
				Method:  http.MethodPost,
				Path:    "/auth/sms/send",
				Handler: auth.SendSmsCodeHandler(serverCtx),
			},
			{
				// Refresh token
				Method:  http.MethodPost,
				Path:    "/auth/token/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get file URL
				Method:  http.MethodGet,
				Path:    "/file/:file_id",
				Handler: file.GetFileUrlHandler(serverCtx),
			},
			{
				// Upload file to MinIO
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: file.UploadFileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get permission tree
				Method:  http.MethodGet,
				Path:    "/permissions",
				Handler: permission.GetPermissionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Unbind property from user
				Method:  http.MethodDelete,
				Path:    "/property/:id",
				Handler: property.UnbindPropertyHandler(serverCtx),
			},
			{
				// Bind property to user
				Method:  http.MethodPost,
				Path:    "/property/bind",
				Handler: property.BindPropertyHandler(serverCtx),
			},
			{
				// Get my properties
				Method:  http.MethodGet,
				Path:    "/property/my",
				Handler: property.GetMyPropertiesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List roles
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: role.GetRolesHandler(serverCtx),
			},
			{
				// Create role
				Method:  http.MethodPost,
				Path:    "/roles",
				Handler: role.CreateRoleHandler(serverCtx),
			},
			{
				// Get role details
				Method:  http.MethodGet,
				Path:    "/roles/:id",
				Handler: role.GetRoleHandler(serverCtx),
			},
			{
				// Update role
				Method:  http.MethodPut,
				Path:    "/roles/:id",
				Handler: role.UpdateRoleHandler(serverCtx),
			},
			{
				// Delete role
				Method:  http.MethodDelete,
				Path:    "/roles/:id",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List users
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				// Create user
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				// Get user details
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				// Update user
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				// Delete user
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				// Get user permissions
				Method:  http.MethodGet,
				Path:    "/users/:id/permissions",
				Handler: user.GetUserPermissionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Submit homeowner verification
				Method:  http.MethodPost,
				Path:    "/verification",
				Handler: verification.SubmitVerificationHandler(serverCtx),
			},
			{
				// Get verification details
				Method:  http.MethodGet,
				Path:    "/verification/:id",
				Handler: verification.GetVerificationHandler(serverCtx),
			},
			{
				// Review verification request (admin)
				Method:  http.MethodPut,
				Path:    "/verification/:id/review",
				Handler: verification.ReviewVerificationHandler(serverCtx),
			},
			{
				// Get my verification requests
				Method:  http.MethodGet,
				Path:    "/verification/my",
				Handler: verification.GetMyVerificationsHandler(serverCtx),
			},
			{
				// List all verification requests (admin)
				Method:  http.MethodGet,
				Path:    "/verifications",
				Handler: verification.GetVerificationListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create family
				Method:  http.MethodPost,
				Path:    "/family",
				Handler: family.CreateFamilyHandler(serverCtx),
			},
			{
				// Get family details
				Method:  http.MethodGet,
				Path:    "/family/:id",
				Handler: family.GetFamilyHandler(serverCtx),
			},
			{
				// Update family
				Method:  http.MethodPut,
				Path:    "/family/:id",
				Handler: family.UpdateFamilyHandler(serverCtx),
			},
			{
				// Delete family
				Method:  http.MethodDelete,
				Path:    "/family/:id",
				Handler: family.DeleteFamilyHandler(serverCtx),
			},
			{
				// Get families by property unit
				Method:  http.MethodGet,
				Path:    "/family/property/:property_unit_id",
				Handler: family.GetPropertyFamiliesHandler(serverCtx),
			},
			{
				// Add family member
				Method:  http.MethodPost,
				Path:    "/family/:id/members",
				Handler: family.AddFamilyMemberHandler(serverCtx),
			},
			{
				// Get family members
				Method:  http.MethodGet,
				Path:    "/family/:id/members",
				Handler: family.GetFamilyMembersHandler(serverCtx),
			},
			{
				// Update family member
				Method:  http.MethodPut,
				Path:    "/family/members/:member_id",
				Handler: family.UpdateFamilyMemberHandler(serverCtx),
			},
			{
				// Delete family member
				Method:  http.MethodDelete,
				Path:    "/family/members/:member_id",
				Handler: family.DeleteFamilyMemberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/identity"),
	)
}
